/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    categories: Category;
    media: Media;
    pages: Page;
    bidangs: Bidang;
    units: Unit;
    officers: Officer;
    'agenda-books': AgendaBook;
    'incoming-mails': IncomingMail;
    'outgoing-mails': OutgoingMail;
    dispositions: Disposition;
    'administrative-documents': AdministrativeDocument;
    'document-archives': DocumentArchive;
    programs: Program;
    'program-schedules': ProgramSchedule;
    'program-committees': ProgramCommittee;
    participants: Participant;
    attendances: Attendance;
    'program-documentations': ProgramDocumentation;
    'wajib-khidmah-lembagas': WajibKhidmahLembagas;
    'wajib-khidmah-members': WajibKhidmahMember;
    'falak-prayer-times': FalakPrayerTime;
    'falak-qiblas': FalakQibla;
    'falak-hijri-calendars': FalakHijriCalendar;
    'falak-hisabs': FalakHisab;
    'falak-rukyats': FalakRukyat;
    'falak-eclipses': FalakEclipse;
    'google-drive-connections': GoogleDriveConnection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    bidangs: BidangsSelect<false> | BidangsSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    officers: OfficersSelect<false> | OfficersSelect<true>;
    'agenda-books': AgendaBooksSelect<false> | AgendaBooksSelect<true>;
    'incoming-mails': IncomingMailsSelect<false> | IncomingMailsSelect<true>;
    'outgoing-mails': OutgoingMailsSelect<false> | OutgoingMailsSelect<true>;
    dispositions: DispositionsSelect<false> | DispositionsSelect<true>;
    'administrative-documents': AdministrativeDocumentsSelect<false> | AdministrativeDocumentsSelect<true>;
    'document-archives': DocumentArchivesSelect<false> | DocumentArchivesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'program-schedules': ProgramSchedulesSelect<false> | ProgramSchedulesSelect<true>;
    'program-committees': ProgramCommitteesSelect<false> | ProgramCommitteesSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    attendances: AttendancesSelect<false> | AttendancesSelect<true>;
    'program-documentations': ProgramDocumentationsSelect<false> | ProgramDocumentationsSelect<true>;
    'wajib-khidmah-lembagas': WajibKhidmahLembagasSelect<false> | WajibKhidmahLembagasSelect<true>;
    'wajib-khidmah-members': WajibKhidmahMembersSelect<false> | WajibKhidmahMembersSelect<true>;
    'falak-prayer-times': FalakPrayerTimesSelect<false> | FalakPrayerTimesSelect<true>;
    'falak-qiblas': FalakQiblasSelect<false> | FalakQiblasSelect<true>;
    'falak-hijri-calendars': FalakHijriCalendarsSelect<false> | FalakHijriCalendarsSelect<true>;
    'falak-hisabs': FalakHisabsSelect<false> | FalakHisabsSelect<true>;
    'falak-rukyats': FalakRukyatsSelect<false> | FalakRukyatsSelect<true>;
    'falak-eclipses': FalakEclipsesSelect<false> | FalakEclipsesSelect<true>;
    'google-drive-connections': GoogleDriveConnectionsSelect<false> | GoogleDriveConnectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'organization-structure': OrganizationStructure;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'organization-structure': OrganizationStructureSelect<false> | OrganizationStructureSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('super-admin' | 'administrator' | 'editor' | 'operator' | 'sekretaris' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: string | null;
  thumbnail?: string | null;
  category?: (number | null) | Category;
  published?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  originalName: string;
  mimeType: string;
  size: number;
  url?: string | null;
  access?: ('public' | 'private') | null;
  fileId: string;
  folder: string;
  storageProvider: 'BLOB' | 'GOOGLE_DRIVE';
  storageKey?: string | null;
  uploadedById?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Konten halaman situs. Skema field per key ada di config/site-pages.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Identifier halaman (unik).
   */
  key:
    | 'homepage.about'
    | 'page:profil'
    | 'page:tentang'
    | 'page:visi-misi'
    | 'page:falak'
    | 'page:kontak'
    | 'page:tim-wajib-khidmah';
  /**
   * Nilai field halaman (teks, list, dll) sesuai skema di config/site-pages.ts.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bidang-bidang kegiatan yang ditampilkan pada halaman profil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bidangs".
 */
export interface Bidang {
  id: number;
  slug: string;
  title: string;
  tagline?: string | null;
  description?: string | null;
  points?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Struktur organisasi: PP, PW, dan PC (Pendataan).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  code: string;
  name: string;
  level: 'PP' | 'PW' | 'PC';
  parent?: (number | null) | Unit;
  sortOrder?: number | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Petugas/unit pengurus untuk tiap unit organisasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers".
 */
export interface Officer {
  id: number;
  unit: number | Unit;
  name: string;
  position: string;
  isLeader?: boolean | null;
  phone?: string | null;
  email?: string | null;
  sortOrder?: number | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Buku agenda kegiatan sekretariat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-books".
 */
export interface AgendaBook {
  id: number;
  date: string;
  title: string;
  description?: string | null;
  location?: string | null;
  participants?: string | null;
  notes?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Surat masuk sekretariat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incoming-mails".
 */
export interface IncomingMail {
  id: number;
  registrationNumber: string;
  sender: string;
  subject: string;
  senderAddress?: string | null;
  receivedDate: string;
  status: 'RECEIVED' | 'PROCESSED' | 'ARCHIVED';
  classification?: string | null;
  category?: string | null;
  notes?: string | null;
  attachmentUrl?: string | null;
  archivedAt?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Surat keluar sekretariat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outgoing-mails".
 */
export interface OutgoingMail {
  id: number;
  registrationNumber: string;
  recipient?: string | null;
  subject: string;
  senderName?: string | null;
  mailDate: string;
  status: 'DRAFT' | 'SENT' | 'ARCHIVED';
  documentType?:
    | (
        | 'UNDANGAN'
        | 'PERMOHONAN'
        | 'PEMBERITAHUAN'
        | 'INSTRUKSI'
        | 'KETERANGAN'
        | 'KEPUTUSAN'
        | 'TERIMA_KASIH'
        | 'LAINNYA'
      )
    | null;
  categoryCode?: string | null;
  content?: string | null;
  sentAt?: string | null;
  archivedAt?: string | null;
  sequence?: number | null;
  levelCode?: string | null;
  romanMonth?: string | null;
  periodYear?: number | null;
  fullNumber?: string | null;
  verificationCode?: string | null;
  qrFileId?: string | null;
  attachmentUrl?: string | null;
  ketuaName?: string | null;
  ketuaPosition?: string | null;
  sekretarisName?: string | null;
  sekretarisPosition?: string | null;
  qrKetuaPosition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qrSekretarisPosition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qrVerifikasiPosition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Disposisi surat masuk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dispositions".
 */
export interface Disposition {
  id: number;
  incomingMail: number | IncomingMail;
  assignedToId: string;
  instruction: string;
  priority: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  dueDate?: string | null;
  notes?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dokumen administrasi sekretariat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrative-documents".
 */
export interface AdministrativeDocument {
  id: number;
  documentNumber: string;
  documentType:
    'UNDANGAN' | 'PERMOHONAN' | 'PEMBERITAHUAN' | 'INSTRUKSI' | 'KETERANGAN' | 'KEPUTUSAN' | 'TERIMA_KASIH' | 'LAINNYA';
  title: string;
  description?: string | null;
  content?: string | null;
  attachmentUrl?: string | null;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'ARCHIVED';
  submittedById?: string | null;
  submittedAt?: string | null;
  approvedById?: string | null;
  approvedAt?: string | null;
  archivedAt?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Arsip dokumen (read-only).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-archives".
 */
export interface DocumentArchive {
  id: number;
  archiveNumber: string;
  title: string;
  documentType:
    'UNDANGAN' | 'PERMOHONAN' | 'PEMBERITAHUAN' | 'INSTRUKSI' | 'KETERANGAN' | 'KEPUTUSAN' | 'TERIMA_KASIH' | 'LAINNYA';
  category?: string | null;
  retentionYear?: number | null;
  archivedAt: string;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  code: string;
  name: string;
  type: string;
  description?: string | null;
  organizerId?: string | null;
  personInChargeId?: string | null;
  status:
    | 'DRAFT'
    | 'PUBLISHED'
    | 'REGISTRATION_OPEN'
    | 'REGISTRATION_CLOSED'
    | 'ON_GOING'
    | 'COMPLETED'
    | 'CANCELLED'
    | 'ARCHIVED';
  registrationOpen?: string | null;
  registrationClose?: string | null;
  startDate: string;
  endDate: string;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-schedules".
 */
export interface ProgramSchedule {
  id: number;
  program: number | Program;
  title: string;
  venueId?: string | null;
  startTime: string;
  endTime: string;
  description?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-committees".
 */
export interface ProgramCommittee {
  id: number;
  program: number | Program;
  userId: string;
  role: string;
  status: 'ACTIVE' | 'INACTIVE';
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  program: number | Program;
  userId: string;
  registrationDate: string;
  registrationStatus: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendances".
 */
export interface Attendance {
  id: number;
  participant: number | Participant;
  checkIn?: string | null;
  checkOut?: string | null;
  status: 'PRESENT' | 'ABSENT' | 'LATE' | 'EXCUSED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-documentations".
 */
export interface ProgramDocumentation {
  id: number;
  program: number | Program;
  media?: (number | null) | Media;
  title: string;
  description?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wajib-khidmah-lembagas".
 */
export interface WajibKhidmahLembagas {
  id: number;
  namaLembagaPendidikan: string;
  rtRw?: string | null;
  desaKelurahan?: string | null;
  kecamatan?: string | null;
  kabupatenKota?: string | null;
  provinsi?: string | null;
  teleponLembaga?: string | null;
  mediaSosialLembaga?: string | null;
  pengasuhNama?: string | null;
  pengasuhStatus?: ('ALUMNI_LIRBOYO' | 'BUKAN_ALUMNI' | 'WALI_SANTRI' | 'LAINNYA') | null;
  pengasuhStatusLainnya?: string | null;
  pengasuhAlumniAngkatan?: string | null;
  pengasuhTelepon?: string | null;
  pengasuhFotoFileId?: string | null;
  penanggungJawabNama?: string | null;
  penanggungJawabStatus?: ('ALUMNI_LIRBOYO' | 'BUKAN_ALUMNI' | 'WALI_SANTRI' | 'LAINNYA') | null;
  penanggungJawabStatusLainnya?: string | null;
  penanggungJawabAlumniAngkatan?: string | null;
  penanggungJawabTelepon?: string | null;
  penanggungJawabFotoFileId?: string | null;
  lokasiMadrasah?: ('DALAM_PESANTREN' | 'LUAR_PESANTREN') | null;
  jenisSatuanPendidikan?:
    | (
        | 'TPQ'
        | 'MADRASAH_DINIYAH'
        | 'MI'
        | 'MTS'
        | 'MA'
        | 'SD_PESANTREN'
        | 'SMP_PESANTREN'
        | 'SMA_PESANTREN'
        | 'KMI'
        | 'PDF'
        | 'LAINNYA'
      )[]
    | null;
  jenisSatuanPendidikanLainnya?: string | null;
  kitabBermakna?:
    | {
        kitab?: string | null;
        id?: string | null;
      }[]
    | null;
  kitabBermaknaLainnya?: string | null;
  bahasaPengantar?:
    | {
        bahasa?: string | null;
        id?: string | null;
      }[]
    | null;
  bahasaPengantarLainnya?: string | null;
  jumlahPengurusPutra?: number | null;
  jumlahPengurusPutri?: number | null;
  jumlahSantriPutra?: number | null;
  jumlahSantriPutri?: number | null;
  jumlahGuruBantuDimohon: number;
  tugasGuruBantu?: string | null;
  kitabDiajarkanGuruBantu?: string | null;
  catatanCalonGuruBantu?: string | null;
  dokumenPermohonanFileId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wajib-khidmah-members".
 */
export interface WajibKhidmahMember {
  id: number;
  nama: string;
  asalDaerah?: string | null;
  alamatLembaga?: string | null;
  posWajibKhidmah?: string | null;
  tempatWajibKhidmah?:
    | {
        tempat?: string | null;
        id?: string | null;
      }[]
    | null;
  tugasKhidmah?: string | null;
  status: 'AKTIF' | 'GUGUR' | 'BEBAS_TUGAS' | 'QODLO';
  keterangan?: string | null;
  catatan?: string | null;
  absensi?: string | null;
  lembaga?: (number | null) | WajibKhidmahLembagas;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-prayer-times".
 */
export interface FalakPrayerTime {
  id: number;
  locationName: string;
  latitude: number;
  longitude: number;
  timezone: string;
  calculationMethod: 'KEMENAG' | 'MUHAMMADIYAH' | 'UMMAH_AL_QURA' | 'EGYPTIAN' | 'ISNA' | 'MWL';
  prayerDate: string;
  fajr: string;
  sunrise: string;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-qiblas".
 */
export interface FalakQibla {
  id: number;
  latitude: number;
  longitude: number;
  direction: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-hijri-calendars".
 */
export interface FalakHijriCalendar {
  id: number;
  gregorianDate: string;
  hijriYear: number;
  hijriMonth: number;
  hijriDay: number;
  method: 'HISAB' | 'RUKYAT' | 'IMKANUR_RUKYAT' | 'WUJUDUL_HILAL';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-hisabs".
 */
export interface FalakHisab {
  id: number;
  calculationDate: string;
  locationName: string;
  latitude: number;
  longitude: number;
  parameters:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  result:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  calculatedById?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-rukyats".
 */
export interface FalakRukyat {
  id: number;
  observationDate: string;
  locationName: string;
  latitude: number;
  longitude: number;
  observerId: string;
  weather: string;
  result: 'VISIBLE' | 'NOT_VISIBLE' | 'CLOUDY' | 'UNKNOWN';
  notes?: string | null;
  status: 'DRAFT' | 'VERIFIED' | 'CONFIRMED' | 'ARCHIVED';
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-eclipses".
 */
export interface FalakEclipse {
  id: number;
  eclipseType: 'SOLAR' | 'LUNAR';
  eclipseDate: string;
  visibility?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Koneksi OAuth Google Drive (token arsip surat).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-drive-connections".
 */
export interface GoogleDriveConnection {
  id: number;
  email: string;
  refreshToken: string;
  driveFolderId?: string | null;
  driveFolderName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'bidangs';
        value: number | Bidang;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'officers';
        value: number | Officer;
      } | null)
    | ({
        relationTo: 'agenda-books';
        value: number | AgendaBook;
      } | null)
    | ({
        relationTo: 'incoming-mails';
        value: number | IncomingMail;
      } | null)
    | ({
        relationTo: 'outgoing-mails';
        value: number | OutgoingMail;
      } | null)
    | ({
        relationTo: 'dispositions';
        value: number | Disposition;
      } | null)
    | ({
        relationTo: 'administrative-documents';
        value: number | AdministrativeDocument;
      } | null)
    | ({
        relationTo: 'document-archives';
        value: number | DocumentArchive;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'program-schedules';
        value: number | ProgramSchedule;
      } | null)
    | ({
        relationTo: 'program-committees';
        value: number | ProgramCommittee;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'attendances';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'program-documentations';
        value: number | ProgramDocumentation;
      } | null)
    | ({
        relationTo: 'wajib-khidmah-lembagas';
        value: number | WajibKhidmahLembagas;
      } | null)
    | ({
        relationTo: 'wajib-khidmah-members';
        value: number | WajibKhidmahMember;
      } | null)
    | ({
        relationTo: 'falak-prayer-times';
        value: number | FalakPrayerTime;
      } | null)
    | ({
        relationTo: 'falak-qiblas';
        value: number | FalakQibla;
      } | null)
    | ({
        relationTo: 'falak-hijri-calendars';
        value: number | FalakHijriCalendar;
      } | null)
    | ({
        relationTo: 'falak-hisabs';
        value: number | FalakHisab;
      } | null)
    | ({
        relationTo: 'falak-rukyats';
        value: number | FalakRukyat;
      } | null)
    | ({
        relationTo: 'falak-eclipses';
        value: number | FalakEclipse;
      } | null)
    | ({
        relationTo: 'google-drive-connections';
        value: number | GoogleDriveConnection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  thumbnail?: T;
  category?: T;
  published?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  originalName?: T;
  mimeType?: T;
  size?: T;
  url?: T;
  access?: T;
  fileId?: T;
  folder?: T;
  storageProvider?: T;
  storageKey?: T;
  uploadedById?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  key?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bidangs_select".
 */
export interface BidangsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  tagline?: T;
  description?: T;
  points?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  level?: T;
  parent?: T;
  sortOrder?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers_select".
 */
export interface OfficersSelect<T extends boolean = true> {
  unit?: T;
  name?: T;
  position?: T;
  isLeader?: T;
  phone?: T;
  email?: T;
  sortOrder?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-books_select".
 */
export interface AgendaBooksSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  description?: T;
  location?: T;
  participants?: T;
  notes?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incoming-mails_select".
 */
export interface IncomingMailsSelect<T extends boolean = true> {
  registrationNumber?: T;
  sender?: T;
  subject?: T;
  senderAddress?: T;
  receivedDate?: T;
  status?: T;
  classification?: T;
  category?: T;
  notes?: T;
  attachmentUrl?: T;
  archivedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outgoing-mails_select".
 */
export interface OutgoingMailsSelect<T extends boolean = true> {
  registrationNumber?: T;
  recipient?: T;
  subject?: T;
  senderName?: T;
  mailDate?: T;
  status?: T;
  documentType?: T;
  categoryCode?: T;
  content?: T;
  sentAt?: T;
  archivedAt?: T;
  sequence?: T;
  levelCode?: T;
  romanMonth?: T;
  periodYear?: T;
  fullNumber?: T;
  verificationCode?: T;
  qrFileId?: T;
  attachmentUrl?: T;
  ketuaName?: T;
  ketuaPosition?: T;
  sekretarisName?: T;
  sekretarisPosition?: T;
  qrKetuaPosition?: T;
  qrSekretarisPosition?: T;
  qrVerifikasiPosition?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dispositions_select".
 */
export interface DispositionsSelect<T extends boolean = true> {
  incomingMail?: T;
  assignedToId?: T;
  instruction?: T;
  priority?: T;
  status?: T;
  dueDate?: T;
  notes?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrative-documents_select".
 */
export interface AdministrativeDocumentsSelect<T extends boolean = true> {
  documentNumber?: T;
  documentType?: T;
  title?: T;
  description?: T;
  content?: T;
  attachmentUrl?: T;
  status?: T;
  submittedById?: T;
  submittedAt?: T;
  approvedById?: T;
  approvedAt?: T;
  archivedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-archives_select".
 */
export interface DocumentArchivesSelect<T extends boolean = true> {
  archiveNumber?: T;
  title?: T;
  documentType?: T;
  category?: T;
  retentionYear?: T;
  archivedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  type?: T;
  description?: T;
  organizerId?: T;
  personInChargeId?: T;
  status?: T;
  registrationOpen?: T;
  registrationClose?: T;
  startDate?: T;
  endDate?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-schedules_select".
 */
export interface ProgramSchedulesSelect<T extends boolean = true> {
  program?: T;
  title?: T;
  venueId?: T;
  startTime?: T;
  endTime?: T;
  description?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-committees_select".
 */
export interface ProgramCommitteesSelect<T extends boolean = true> {
  program?: T;
  userId?: T;
  role?: T;
  status?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  program?: T;
  userId?: T;
  registrationDate?: T;
  registrationStatus?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendances_select".
 */
export interface AttendancesSelect<T extends boolean = true> {
  participant?: T;
  checkIn?: T;
  checkOut?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-documentations_select".
 */
export interface ProgramDocumentationsSelect<T extends boolean = true> {
  program?: T;
  media?: T;
  title?: T;
  description?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wajib-khidmah-lembagas_select".
 */
export interface WajibKhidmahLembagasSelect<T extends boolean = true> {
  namaLembagaPendidikan?: T;
  rtRw?: T;
  desaKelurahan?: T;
  kecamatan?: T;
  kabupatenKota?: T;
  provinsi?: T;
  teleponLembaga?: T;
  mediaSosialLembaga?: T;
  pengasuhNama?: T;
  pengasuhStatus?: T;
  pengasuhStatusLainnya?: T;
  pengasuhAlumniAngkatan?: T;
  pengasuhTelepon?: T;
  pengasuhFotoFileId?: T;
  penanggungJawabNama?: T;
  penanggungJawabStatus?: T;
  penanggungJawabStatusLainnya?: T;
  penanggungJawabAlumniAngkatan?: T;
  penanggungJawabTelepon?: T;
  penanggungJawabFotoFileId?: T;
  lokasiMadrasah?: T;
  jenisSatuanPendidikan?: T;
  jenisSatuanPendidikanLainnya?: T;
  kitabBermakna?:
    | T
    | {
        kitab?: T;
        id?: T;
      };
  kitabBermaknaLainnya?: T;
  bahasaPengantar?:
    | T
    | {
        bahasa?: T;
        id?: T;
      };
  bahasaPengantarLainnya?: T;
  jumlahPengurusPutra?: T;
  jumlahPengurusPutri?: T;
  jumlahSantriPutra?: T;
  jumlahSantriPutri?: T;
  jumlahGuruBantuDimohon?: T;
  tugasGuruBantu?: T;
  kitabDiajarkanGuruBantu?: T;
  catatanCalonGuruBantu?: T;
  dokumenPermohonanFileId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wajib-khidmah-members_select".
 */
export interface WajibKhidmahMembersSelect<T extends boolean = true> {
  nama?: T;
  asalDaerah?: T;
  alamatLembaga?: T;
  posWajibKhidmah?: T;
  tempatWajibKhidmah?:
    | T
    | {
        tempat?: T;
        id?: T;
      };
  tugasKhidmah?: T;
  status?: T;
  keterangan?: T;
  catatan?: T;
  absensi?: T;
  lembaga?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-prayer-times_select".
 */
export interface FalakPrayerTimesSelect<T extends boolean = true> {
  locationName?: T;
  latitude?: T;
  longitude?: T;
  timezone?: T;
  calculationMethod?: T;
  prayerDate?: T;
  fajr?: T;
  sunrise?: T;
  dhuhr?: T;
  asr?: T;
  maghrib?: T;
  isha?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-qiblas_select".
 */
export interface FalakQiblasSelect<T extends boolean = true> {
  latitude?: T;
  longitude?: T;
  direction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-hijri-calendars_select".
 */
export interface FalakHijriCalendarsSelect<T extends boolean = true> {
  gregorianDate?: T;
  hijriYear?: T;
  hijriMonth?: T;
  hijriDay?: T;
  method?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-hisabs_select".
 */
export interface FalakHisabsSelect<T extends boolean = true> {
  calculationDate?: T;
  locationName?: T;
  latitude?: T;
  longitude?: T;
  parameters?: T;
  result?: T;
  calculatedById?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-rukyats_select".
 */
export interface FalakRukyatsSelect<T extends boolean = true> {
  observationDate?: T;
  locationName?: T;
  latitude?: T;
  longitude?: T;
  observerId?: T;
  weather?: T;
  result?: T;
  notes?: T;
  status?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "falak-eclipses_select".
 */
export interface FalakEclipsesSelect<T extends boolean = true> {
  eclipseType?: T;
  eclipseDate?: T;
  visibility?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-drive-connections_select".
 */
export interface GoogleDriveConnectionsSelect<T extends boolean = true> {
  email?: T;
  refreshToken?: T;
  driveFolderId?: T;
  driveFolderName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  numbering?: {
    /**
     * Template format nomor surat keluar (placeholder: {seq}, {level}, {category}, {bulan}, {tahun}).
     */
    formatTemplate?: string | null;
    /**
     * Jumlah digit nomor urut (padding, mis. 3 => 001).
     */
    sequenceDigits?: number | null;
    periods?:
      | {
          startYear: number;
          endYear: number;
          id?: string | null;
        }[]
      | null;
    levelCodes?:
      | {
          code: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Override nomor urut berikutnya per periode ({"periodYear": n}).
     */
    nextSequence?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    tagline?: string | null;
    description?: string | null;
    image?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
    statCards?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Struktur organisasi: info organisasi, google sheet URL, pengurus pusat, wilayah, cabang, anggota.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-structure".
 */
export interface OrganizationStructure {
  id: number;
  organization: {
    name: string;
    shortName?: string | null;
    logo?: string | null;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    website?: string | null;
  };
  googleSheetUrl?: string | null;
  centralBoard?:
    | {
        id: string;
        name: string;
        position: string;
        image?: string | null;
        sortOrder?: number | null;
      }[]
    | null;
  regionalBoards?:
    | {
        id: string;
        province: string;
        name: string;
        members?:
          | {
              id: string;
              name: string;
              position: string;
              image?: string | null;
              sortOrder?: number | null;
            }[]
          | null;
      }[]
    | null;
  branchBoards?:
    | {
        id: string;
        province: string;
        regency: string;
        name: string;
        members?:
          | {
              id: string;
              name: string;
              position: string;
              image?: string | null;
              sortOrder?: number | null;
            }[]
          | null;
      }[]
    | null;
  members?:
    | {
        id: string;
        name: string;
        position: string;
        image?: string | null;
        sortOrder?: number | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  numbering?:
    | T
    | {
        formatTemplate?: T;
        sequenceDigits?: T;
        periods?:
          | T
          | {
              startYear?: T;
              endYear?: T;
              id?: T;
            };
        levelCodes?:
          | T
          | {
              code?: T;
              label?: T;
              id?: T;
            };
        nextSequence?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        tagline?: T;
        description?: T;
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        statCards?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-structure_select".
 */
export interface OrganizationStructureSelect<T extends boolean = true> {
  organization?:
    | T
    | {
        name?: T;
        shortName?: T;
        logo?: T;
        address?: T;
        phone?: T;
        email?: T;
        website?: T;
      };
  googleSheetUrl?: T;
  centralBoard?:
    | T
    | {
        id?: T;
        name?: T;
        position?: T;
        image?: T;
        sortOrder?: T;
      };
  regionalBoards?:
    | T
    | {
        id?: T;
        province?: T;
        name?: T;
        members?:
          | T
          | {
              id?: T;
              name?: T;
              position?: T;
              image?: T;
              sortOrder?: T;
            };
      };
  branchBoards?:
    | T
    | {
        id?: T;
        province?: T;
        regency?: T;
        name?: T;
        members?:
          | T
          | {
              id?: T;
              name?: T;
              position?: T;
              image?: T;
              sortOrder?: T;
            };
      };
  members?:
    | T
    | {
        id?: T;
        name?: T;
        position?: T;
        image?: T;
        sortOrder?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}