import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres";

export async function up({
  db,
  payload,
  req,
}: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "payload_settings_numbering_periods" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_settings_numbering_periods" ALTER COLUMN "id" TYPE varchar;
  ALTER TABLE "payload_settings_numbering_level_codes" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_settings_numbering_level_codes" ALTER COLUMN "id" TYPE varchar;
  ALTER TABLE "payload_settings_hero_stat_cards" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_settings_hero_stat_cards" ALTER COLUMN "id" TYPE varchar;`);
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "payload_settings_numbering_periods" ALTER COLUMN "id" TYPE integer;
  ALTER TABLE "payload_settings_numbering_periods" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  ALTER TABLE "payload_settings_numbering_level_codes" ALTER COLUMN "id" TYPE integer;
  ALTER TABLE "payload_settings_numbering_level_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  ALTER TABLE "payload_settings_hero_stat_cards" ALTER COLUMN "id" TYPE integer;
  ALTER TABLE "payload_settings_hero_stat_cards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;`);
}