export interface City {
  name: string;
  province: string;
  latitude: number;
  longitude: number;
  timezone: number; // +7 (WIB), +8 (WITA), +9 (WIT)
  timezoneName: string; // WIB, WITA, WIT
}

export const INDONESIA_CITIES: City[] = [

  // --- ACEH ---
  { name: 'Tapak Tuan (Aceh Selatan)', province: 'Aceh', latitude: 3.2548, longitude: 97.1741, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kutacane (Aceh Tenggara)', province: 'Aceh', latitude: 3.4734, longitude: 97.8192, timezone: 7, timezoneName: 'WIB' },
  { name: 'Idi Rayeuk (Aceh Timur)', province: 'Aceh', latitude: 4.9327, longitude: 97.7838, timezone: 7, timezoneName: 'WIB' },
  { name: 'Takengon (Aceh Tengah)', province: 'Aceh', latitude: 4.6221, longitude: 96.8457, timezone: 7, timezoneName: 'WIB' },
  { name: 'Meulaboh (Aceh Barat)', province: 'Aceh', latitude: 4.1530, longitude: 96.1314, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kota Jantho (Aceh Besar)', province: 'Aceh', latitude: 5.2973, longitude: 95.6109, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sigli (Pidie)', province: 'Aceh', latitude: 5.3676, longitude: 95.9579, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lhoksukon (Aceh Utara)', province: 'Aceh', latitude: 5.0757, longitude: 97.3026, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sinabang (Simeulue)', province: 'Aceh', latitude: 2.4614, longitude: 96.3804, timezone: 7, timezoneName: 'WIB' },
  { name: 'Singkil (Aceh Singkil)', province: 'Aceh', latitude: 2.2711, longitude: 97.8153, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bireuen (Bireuen)', province: 'Aceh', latitude: 5.2076, longitude: 96.7264, timezone: 7, timezoneName: 'WIB' },
  { name: 'Blangpidie (Aceh Barat Daya)', province: 'Aceh', latitude: 3.7391, longitude: 96.8515, timezone: 7, timezoneName: 'WIB' },
  { name: 'Blang Kejeren (Gayo Lues)', province: 'Aceh', latitude: 3.9935, longitude: 97.3245, timezone: 7, timezoneName: 'WIB' },
  { name: 'Calang (Aceh Jaya)', province: 'Aceh', latitude: 4.6241, longitude: 95.6168, timezone: 7, timezoneName: 'WIB' },
  { name: 'Suka Makmue (Nagan Raya)', province: 'Aceh', latitude: 4.1694, longitude: 96.3244, timezone: 7, timezoneName: 'WIB' },
  { name: 'Karang Baru (Aceh Tamiang)', province: 'Aceh', latitude: 4.3013, longitude: 98.0457, timezone: 7, timezoneName: 'WIB' },
  { name: 'Simpang Tiga Redelong (Bener Meriah)', province: 'Aceh', latitude: 4.7028, longitude: 96.8620, timezone: 7, timezoneName: 'WIB' },
  { name: 'Meureudu (Pidie Jaya)', province: 'Aceh', latitude: 5.2289, longitude: 96.2448, timezone: 7, timezoneName: 'WIB' },
  { name: 'Banda Aceh', province: 'Aceh', latitude: 5.5500, longitude: 95.3178, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sabang', province: 'Aceh', latitude: 5.8927, longitude: 95.3211, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lhokseumawe', province: 'Aceh', latitude: 5.1794, longitude: 97.1489, timezone: 7, timezoneName: 'WIB' },
  { name: 'Langsa', province: 'Aceh', latitude: 4.4695, longitude: 97.9664, timezone: 7, timezoneName: 'WIB' },
  { name: 'Subulussalam', province: 'Aceh', latitude: 2.6708, longitude: 97.9930, timezone: 7, timezoneName: 'WIB' },

  // --- SUMATERA UTARA ---
  { name: 'Pandan (Tapanuli Tengah)', province: 'Sumatera Utara', latitude: 1.6847, longitude: 98.8277, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tarutung (Tapanuli Utara)', province: 'Sumatera Utara', latitude: 2.0218, longitude: 98.9618, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sipirok (Tapanuli Selatan)', province: 'Sumatera Utara', latitude: 1.5197, longitude: 99.3028, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gido (Nias)', province: 'Sumatera Utara', latitude: 1.2418, longitude: 97.6499, timezone: 7, timezoneName: 'WIB' },
  { name: 'Stabat (Langkat)', province: 'Sumatera Utara', latitude: 3.7427, longitude: 98.4475, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kabanjahe (Karo)', province: 'Sumatera Utara', latitude: 3.1107, longitude: 98.5013, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lubuk Pakam (Deli Serdang)', province: 'Sumatera Utara', latitude: 3.5507, longitude: 98.8664, timezone: 7, timezoneName: 'WIB' },
  { name: 'Raya (Simalungun)', province: 'Sumatera Utara', latitude: 2.9653, longitude: 98.8621, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kisaran (Asahan)', province: 'Sumatera Utara', latitude: 2.9881, longitude: 99.6128, timezone: 7, timezoneName: 'WIB' },
  { name: 'Rantau Prapat (Labuhanbatu)', province: 'Sumatera Utara', latitude: 2.0701, longitude: 99.8571, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sidikalang (Dairi)', province: 'Sumatera Utara', latitude: 2.7480, longitude: 98.3140, timezone: 7, timezoneName: 'WIB' },
  { name: 'Balige (Toba)', province: 'Sumatera Utara', latitude: 2.3318, longitude: 99.0510, timezone: 7, timezoneName: 'WIB' },
  { name: 'Panyabungan (Mandailing Natal)', province: 'Sumatera Utara', latitude: 0.7967, longitude: 99.5788, timezone: 7, timezoneName: 'WIB' },
  { name: 'Teluk Dalam (Nias Selatan)', province: 'Sumatera Utara', latitude: 0.5834, longitude: 97.7779, timezone: 7, timezoneName: 'WIB' },
  { name: 'Salak (Pakpak Bharat)', province: 'Sumatera Utara', latitude: 2.5411, longitude: 98.3226, timezone: 7, timezoneName: 'WIB' },
  { name: 'Dolok Sanggul (Humbang Hasundutan)', province: 'Sumatera Utara', latitude: 2.2503, longitude: 98.7905, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pangururan (Samosir)', province: 'Sumatera Utara', latitude: 2.5599, longitude: 98.7224, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sei Rampah (Serdang Bedagai)', province: 'Sumatera Utara', latitude: 3.4913, longitude: 99.1259, timezone: 7, timezoneName: 'WIB' },
  { name: 'Limapuluh (Batu Bara)', province: 'Sumatera Utara', latitude: 3.1718, longitude: 99.4210, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gunung Tua (Padang Lawas Utara)', province: 'Sumatera Utara', latitude: 1.4945, longitude: 99.6197, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sibuhuan (Padang Lawas)', province: 'Sumatera Utara', latitude: 1.0556, longitude: 99.7755, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pinang (Labuhanbatu Selatan)', province: 'Sumatera Utara', latitude: 1.8682, longitude: 100.0411, timezone: 7, timezoneName: 'WIB' },
  { name: 'Aek Kanopan (Labuhanbatu Utara)', province: 'Sumatera Utara', latitude: 2.5628, longitude: 99.6581, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lotu (Nias Utara)', province: 'Sumatera Utara', latitude: 1.3893, longitude: 97.3814, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lahomi (Nias Barat)', province: 'Sumatera Utara', latitude: 0.9990, longitude: 97.4953, timezone: 7, timezoneName: 'WIB' },
  { name: 'Medan', province: 'Sumatera Utara', latitude: 3.5902, longitude: 98.6750, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pematangsiantar', province: 'Sumatera Utara', latitude: 2.9565, longitude: 99.0618, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sibolga', province: 'Sumatera Utara', latitude: 1.7460, longitude: 98.7756, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tanjungbalai', province: 'Sumatera Utara', latitude: 2.9478, longitude: 99.7667, timezone: 7, timezoneName: 'WIB' },
  { name: 'Binjai', province: 'Sumatera Utara', latitude: 3.6030, longitude: 98.4832, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tebing Tinggi', province: 'Sumatera Utara', latitude: 3.3276, longitude: 99.1663, timezone: 7, timezoneName: 'WIB' },
  { name: 'Padangsidimpuan', province: 'Sumatera Utara', latitude: 1.3776, longitude: 99.2714, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gunungsitoli', province: 'Sumatera Utara', latitude: 1.2826, longitude: 97.6135, timezone: 7, timezoneName: 'WIB' },

  // --- SUMATERA BARAT ---
  { name: 'Painan (Pesisir Selatan)', province: 'Sumatera Barat', latitude: -1.3480, longitude: 100.5777, timezone: 7, timezoneName: 'WIB' },
  { name: 'Arosuka (Solok)', province: 'Sumatera Barat', latitude: -0.9516, longitude: 100.6214, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muaro Sijunjung (Sijunjung)', province: 'Sumatera Barat', latitude: -0.6658, longitude: 100.9446, timezone: 7, timezoneName: 'WIB' },
  { name: 'Batusangkar (Tanah Datar)', province: 'Sumatera Barat', latitude: -0.4744, longitude: 100.6234, timezone: 7, timezoneName: 'WIB' },
  { name: 'Parit Malintang (Padang Pariaman)', province: 'Sumatera Barat', latitude: -0.6210, longitude: 100.3065, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lubuk Basung (Agam)', province: 'Sumatera Barat', latitude: -0.3152, longitude: 100.0297, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sarilamak (Lima Puluh Kota)', province: 'Sumatera Barat', latitude: -0.1524, longitude: 100.6607, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lubuk Sikaping (Pasaman)', province: 'Sumatera Barat', latitude: 0.1404, longitude: 100.1670, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tuapejat (Kepulauan Mentawai)', province: 'Sumatera Barat', latitude: -2.0542, longitude: 99.5805, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pulau Punjung (Dharmasraya)', province: 'Sumatera Barat', latitude: -0.9530, longitude: 101.4941, timezone: 7, timezoneName: 'WIB' },
  { name: 'Padang Aro (Solok Selatan)', province: 'Sumatera Barat', latitude: -1.5562, longitude: 101.2395, timezone: 7, timezoneName: 'WIB' },
  { name: 'Simpang Ampek (Pasaman Barat)', province: 'Sumatera Barat', latitude: 0.1104, longitude: 99.8278, timezone: 7, timezoneName: 'WIB' },
  { name: 'Padang', province: 'Sumatera Barat', latitude: -0.8759, longitude: 100.3873, timezone: 7, timezoneName: 'WIB' },
  { name: 'Solok', province: 'Sumatera Barat', latitude: -0.7995, longitude: 100.6528, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sawahlunto', province: 'Sumatera Barat', latitude: -0.6750, longitude: 100.7675, timezone: 7, timezoneName: 'WIB' },
  { name: 'Padang Panjang', province: 'Sumatera Barat', latitude: -0.4621, longitude: 100.3904, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bukittinggi', province: 'Sumatera Barat', latitude: -0.2855, longitude: 100.3678, timezone: 7, timezoneName: 'WIB' },
  { name: 'Payakumbuh', province: 'Sumatera Barat', latitude: -0.2225, longitude: 100.6320, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pariaman', province: 'Sumatera Barat', latitude: -0.6290, longitude: 100.1377, timezone: 7, timezoneName: 'WIB' },

  // --- RIAU ---
  { name: 'Bangkinang (Kampar)', province: 'Riau', latitude: 0.3139, longitude: 101.0180, timezone: 7, timezoneName: 'WIB' },
  { name: 'Rengat (Indragiri Hulu)', province: 'Riau', latitude: -0.3930, longitude: 102.4376, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bengkalis (Bengkalis)', province: 'Riau', latitude: 1.4732, longitude: 102.1133, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tembilahan (Indragiri Hilir)', province: 'Riau', latitude: -0.3152, longitude: 103.1579, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pangkalan Kerinci (Pelalawan)', province: 'Riau', latitude: 0.3838, longitude: 101.8420, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pasir Pengaraian (Rokan Hulu)', province: 'Riau', latitude: 0.8997, longitude: 100.3074, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bagansiapiapi (Rokan Hilir)', province: 'Riau', latitude: 2.0995, longitude: 100.8177, timezone: 7, timezoneName: 'WIB' },
  { name: 'Siak Sri Indrapura (Siak)', province: 'Riau', latitude: 0.8045, longitude: 102.0203, timezone: 7, timezoneName: 'WIB' },
  { name: 'Taluk Kuantan (Kuantan Singingi)', province: 'Riau', latitude: -0.5053, longitude: 101.5381, timezone: 7, timezoneName: 'WIB' },
  { name: 'Selatpanjang (Kepulauan Meranti)', province: 'Riau', latitude: 1.0007, longitude: 102.7257, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pekanbaru', province: 'Riau', latitude: 0.5134, longitude: 101.4470, timezone: 7, timezoneName: 'WIB' },
  { name: 'Dumai', province: 'Riau', latitude: 1.6054, longitude: 101.3917, timezone: 7, timezoneName: 'WIB' },

  // --- JAMBI ---
  { name: 'Siulak (Kerinci)', province: 'Jambi', latitude: -2.0574, longitude: 101.3885, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bangko (Merangin)', province: 'Jambi', latitude: -2.0601, longitude: 102.2743, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sarolangun (Sarolangun)', province: 'Jambi', latitude: -2.3132, longitude: 102.7504, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Bulian (Batanghari)', province: 'Jambi', latitude: -1.6936, longitude: 103.2730, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sengeti (Muaro Jambi)', province: 'Jambi', latitude: -1.4483, longitude: 103.5155, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kuala Tungkal (Tanjung Jabung Barat)', province: 'Jambi', latitude: -0.8267, longitude: 103.4612, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Sabak (Tanjung Jabung Timur)', province: 'Jambi', latitude: -1.2062, longitude: 103.7904, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Bungo (Bungo)', province: 'Jambi', latitude: -1.5163, longitude: 102.1187, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Tebo (Tebo)', province: 'Jambi', latitude: -1.4662, longitude: 102.3583, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jambi', province: 'Jambi', latitude: -1.6305, longitude: 103.6073, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sungai Penuh', province: 'Jambi', latitude: -2.0709, longitude: 101.3961, timezone: 7, timezoneName: 'WIB' },

  // --- SUMATERA SELATAN ---
  { name: 'Baturaja (Ogan Komering Ulu)', province: 'Sumatera Selatan', latitude: -4.1657, longitude: 104.1978, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kayu Agung (Ogan Komering)', province: 'Sumatera Selatan', latitude: -3.4116, longitude: 104.8230, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Enim (Muara Enim)', province: 'Sumatera Selatan', latitude: -3.6556, longitude: 103.7770, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lahat (Lahat)', province: 'Sumatera Selatan', latitude: -3.7782, longitude: 103.5505, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Beliti Baru (Musi Rawas)', province: 'Sumatera Selatan', latitude: -3.2435, longitude: 103.0116, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sekayu (Musi Banyuasin)', province: 'Sumatera Selatan', latitude: -2.8888, longitude: 103.8402, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pangkalan Balai (Banyuasin)', province: 'Sumatera Selatan', latitude: -2.9168, longitude: 104.4066, timezone: 7, timezoneName: 'WIB' },
  { name: 'Martapura (Ogan Komering Ulu Timur)', province: 'Sumatera Selatan', latitude: -4.3688, longitude: 104.3584, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muaradua (Ogan Komering Ulu Selatan)', province: 'Sumatera Selatan', latitude: -4.5323, longitude: 104.0954, timezone: 7, timezoneName: 'WIB' },
  { name: 'Indralaya (Ogan Ilir)', province: 'Sumatera Selatan', latitude: -3.2606, longitude: 104.6525, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tebing Tinggi (Empat Lawang)', province: 'Sumatera Selatan', latitude: -3.6098, longitude: 103.1028, timezone: 7, timezoneName: 'WIB' },
  { name: 'Talang Ubi (Penukal Abab Lematang Ilir)', province: 'Sumatera Selatan', latitude: -3.3099, longitude: 103.8841, timezone: 7, timezoneName: 'WIB' },
  { name: 'Rupit (Musi Rawas Utara)', province: 'Sumatera Selatan', latitude: -2.7347, longitude: 102.9011, timezone: 7, timezoneName: 'WIB' },
  { name: 'Palembang', province: 'Sumatera Selatan', latitude: -2.9910, longitude: 104.7568, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pagar Alam', province: 'Sumatera Selatan', latitude: -4.0393, longitude: 103.1970, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lubuk Linggau', province: 'Sumatera Selatan', latitude: -3.3258, longitude: 102.8254, timezone: 7, timezoneName: 'WIB' },
  { name: 'Prabumulih', province: 'Sumatera Selatan', latitude: -3.3689, longitude: 104.3084, timezone: 7, timezoneName: 'WIB' },

  // --- BENGKULU ---
  { name: 'Manna (Bengkulu Selatan)', province: 'Bengkulu', latitude: -4.4399, longitude: 102.8952, timezone: 7, timezoneName: 'WIB' },
  { name: 'Curup (Rejang Lebong)', province: 'Bengkulu', latitude: -3.4780, longitude: 102.5319, timezone: 7, timezoneName: 'WIB' },
  { name: 'Arga Makmur (Bengkulu Utara)', province: 'Bengkulu', latitude: -3.4369, longitude: 102.2018, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bintuhan (Kaur)', province: 'Bengkulu', latitude: -4.7591, longitude: 103.3491, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tais (Seluma)', province: 'Bengkulu', latitude: -4.0776, longitude: 102.5563, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mukomuko (Mukomuko)', province: 'Bengkulu', latitude: -2.5528, longitude: 101.1042, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Aman (Lebong)', province: 'Bengkulu', latitude: -3.1574, longitude: 102.1828, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kepahiang (Kepahiang)', province: 'Bengkulu', latitude: -3.6251, longitude: 102.5563, timezone: 7, timezoneName: 'WIB' },
  { name: 'Karang Tinggi (Bengkulu Tengah)', province: 'Bengkulu', latitude: -3.7729, longitude: 102.3900, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bengkulu', province: 'Bengkulu', latitude: -3.7928, longitude: 102.2608, timezone: 7, timezoneName: 'WIB' },

  // --- LAMPUNG ---
  { name: 'Kalianda (Lampung Selatan)', province: 'Lampung', latitude: -5.7177, longitude: 105.5853, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gunung Sugih (Lampung Tengah)', province: 'Lampung', latitude: -4.9772, longitude: 105.2101, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kotabumi (Lampung Utara)', province: 'Lampung', latitude: -4.8292, longitude: 104.8874, timezone: 7, timezoneName: 'WIB' },
  { name: 'Liwa (Lampung Barat)', province: 'Lampung', latitude: -5.0190, longitude: 104.0608, timezone: 7, timezoneName: 'WIB' },
  { name: 'Menggala (Tulang Bawang)', province: 'Lampung', latitude: -4.4950, longitude: 105.2202, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kota Agung (Tanggamus)', province: 'Lampung', latitude: -5.4807, longitude: 104.6823, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sukadana (Lampung Timur)', province: 'Lampung', latitude: -5.0482, longitude: 105.5283, timezone: 7, timezoneName: 'WIB' },
  { name: 'Blambangan Umpu (Way Kanan)', province: 'Lampung', latitude: -4.5062, longitude: 104.5113, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gedong Tataan (Pesawaran)', province: 'Lampung', latitude: -5.3975, longitude: 105.0701, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pringsewu (Pringsewu)', province: 'Lampung', latitude: -5.3442, longitude: 105.0064, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mesuji (Mesuji)', province: 'Lampung', latitude: -3.8732, longitude: 105.4279, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tulang Bawang Tengah (Tulang Bawang Barat)', province: 'Lampung', latitude: -4.4994, longitude: 105.1199, timezone: 7, timezoneName: 'WIB' },
  { name: 'Krui (Pesisir Barat)', province: 'Lampung', latitude: -5.1884, longitude: 103.9346, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bandar Lampung', province: 'Lampung', latitude: -5.4296, longitude: 105.2626, timezone: 7, timezoneName: 'WIB' },
  { name: 'Metro', province: 'Lampung', latitude: -5.1137, longitude: 105.3069, timezone: 7, timezoneName: 'WIB' },

  // --- BANGKA BELITUNG ---
  { name: 'Sungai Liat (Bangka)', province: 'Bangka Belitung', latitude: -1.8873, longitude: 106.1048, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tanjung Pandan (Belitung)', province: 'Bangka Belitung', latitude: -2.7423, longitude: 107.6543, timezone: 7, timezoneName: 'WIB' },
  { name: 'Toboali (Bangka Selatan)', province: 'Bangka Belitung', latitude: -3.0197, longitude: 106.5117, timezone: 7, timezoneName: 'WIB' },
  { name: 'Koba (Bangka Tengah)', province: 'Bangka Belitung', latitude: -2.5153, longitude: 106.4159, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muntok (Bangka Barat)', province: 'Bangka Belitung', latitude: -2.0586, longitude: 105.2014, timezone: 7, timezoneName: 'WIB' },
  { name: 'Manggar (Belitung Timur)', province: 'Bangka Belitung', latitude: -2.8833, longitude: 108.2393, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pangkal Pinang', province: 'Bangka Belitung', latitude: -2.1410, longitude: 106.1159, timezone: 7, timezoneName: 'WIB' },

  // --- KEPULAUAN RIAU ---
  { name: 'Bandar Seri Bentan (Bintan)', province: 'Kepulauan Riau', latitude: 1.0867, longitude: 104.5021, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tanjung Balai Karimun (Karimun)', province: 'Kepulauan Riau', latitude: 1.0330, longitude: 103.3758, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ranai (Natuna)', province: 'Kepulauan Riau', latitude: 3.9234, longitude: 108.3369, timezone: 7, timezoneName: 'WIB' },
  { name: 'Daik (Lingga)', province: 'Kepulauan Riau', latitude: -0.2100, longitude: 104.6047, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tarempa (Kepulauan Anambas)', province: 'Kepulauan Riau', latitude: 3.2145, longitude: 106.2487, timezone: 7, timezoneName: 'WIB' },
  { name: 'Batam', province: 'Kepulauan Riau', latitude: 1.1287, longitude: 104.0553, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tanjung Pinang', province: 'Kepulauan Riau', latitude: 0.9653, longitude: 104.4410, timezone: 7, timezoneName: 'WIB' },

  // --- DKI JAKARTA ---
  { name: 'Kepulauan Seribu', province: 'DKI Jakarta', latitude: -5.7465, longitude: 106.6132, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jakarta Pusat', province: 'DKI Jakarta', latitude: -6.1729, longitude: 106.8187, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jakarta Utara', province: 'DKI Jakarta', latitude: -6.1200, longitude: 106.8925, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jakarta Barat', province: 'DKI Jakarta', latitude: -6.1843, longitude: 106.7366, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jakarta Selatan', province: 'DKI Jakarta', latitude: -6.2478, longitude: 106.8076, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jakarta Timur', province: 'DKI Jakarta', latitude: -6.2137, longitude: 106.9440, timezone: 7, timezoneName: 'WIB' },

  // --- JAWA BARAT ---
  { name: 'Cibinong (Bogor)', province: 'Jawa Barat', latitude: -6.4795, longitude: 106.8247, timezone: 7, timezoneName: 'WIB' },
  { name: 'Palabuhanratu (Sukabumi)', province: 'Jawa Barat', latitude: -6.9892, longitude: 106.5502, timezone: 7, timezoneName: 'WIB' },
  { name: 'Cianjur (Cianjur)', province: 'Jawa Barat', latitude: -6.8227, longitude: 107.1395, timezone: 7, timezoneName: 'WIB' },
  { name: 'Soreang (Bandung)', province: 'Jawa Barat', latitude: -7.0219, longitude: 107.5276, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tarogong Kidul (Garut)', province: 'Jawa Barat', latitude: -7.2027, longitude: 107.8861, timezone: 7, timezoneName: 'WIB' },
  { name: 'Singaparna (Tasikmalaya)', province: 'Jawa Barat', latitude: -7.3610, longitude: 108.1131, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ciamis (Ciamis)', province: 'Jawa Barat', latitude: -7.3259, longitude: 108.3514, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kuningan (Kuningan)', province: 'Jawa Barat', latitude: -6.9759, longitude: 108.4831, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sumber (Cirebon)', province: 'Jawa Barat', latitude: -6.7645, longitude: 108.4786, timezone: 7, timezoneName: 'WIB' },
  { name: 'Majalengka (Majalengka)', province: 'Jawa Barat', latitude: -6.8363, longitude: 108.2276, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sumedang Utara (Sumedang)', province: 'Jawa Barat', latitude: -6.8612, longitude: 107.9206, timezone: 7, timezoneName: 'WIB' },
  { name: 'Indramayu (Indramayu)', province: 'Jawa Barat', latitude: -6.3271, longitude: 108.3232, timezone: 7, timezoneName: 'WIB' },
  { name: 'Subang (Subang)', province: 'Jawa Barat', latitude: -6.5713, longitude: 107.7624, timezone: 7, timezoneName: 'WIB' },
  { name: 'Purwakarta (Purwakarta)', province: 'Jawa Barat', latitude: -6.5562, longitude: 107.4413, timezone: 7, timezoneName: 'WIB' },
  { name: 'Karawang Barat (Karawang)', province: 'Jawa Barat', latitude: -6.3016, longitude: 107.3049, timezone: 7, timezoneName: 'WIB' },
  { name: 'Cikarang Pusat (Bekasi)', province: 'Jawa Barat', latitude: -6.2474, longitude: 107.1485, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ngamprah (Bandung Barat)', province: 'Jawa Barat', latitude: -6.8652, longitude: 107.4920, timezone: 7, timezoneName: 'WIB' },
  { name: 'Parigi (Pangandaran)', province: 'Jawa Barat', latitude: -7.6151, longitude: 108.4988, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bogor', province: 'Jawa Barat', latitude: -6.5951, longitude: 106.7941, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sukabumi', province: 'Jawa Barat', latitude: -6.9176, longitude: 106.9319, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bandung', province: 'Jawa Barat', latitude: -6.9107, longitude: 107.6099, timezone: 7, timezoneName: 'WIB' },
  { name: 'Cirebon', province: 'Jawa Barat', latitude: -6.7067, longitude: 108.5582, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bekasi', province: 'Jawa Barat', latitude: -6.2360, longitude: 106.9942, timezone: 7, timezoneName: 'WIB' },
  { name: 'Depok', province: 'Jawa Barat', latitude: -6.3942, longitude: 106.8227, timezone: 7, timezoneName: 'WIB' },
  { name: 'Cimahi', province: 'Jawa Barat', latitude: -6.8708, longitude: 107.5552, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tasikmalaya', province: 'Jawa Barat', latitude: -7.3161, longitude: 108.1970, timezone: 7, timezoneName: 'WIB' },
  { name: 'Banjar', province: 'Jawa Barat', latitude: -7.3622, longitude: 108.5596, timezone: 7, timezoneName: 'WIB' },

  // --- JAWA TENGAH ---
  { name: 'Cilacap (Cilacap)', province: 'Jawa Tengah', latitude: -7.7256, longitude: 109.0095, timezone: 7, timezoneName: 'WIB' },
  { name: 'Purwokerto (Banyumas)', province: 'Jawa Tengah', latitude: -7.4228, longitude: 109.2301, timezone: 7, timezoneName: 'WIB' },
  { name: 'Purbalingga (Purbalingga)', province: 'Jawa Tengah', latitude: -7.3888, longitude: 109.3641, timezone: 7, timezoneName: 'WIB' },
  { name: 'Banjarnegara (Banjarnegara)', province: 'Jawa Tengah', latitude: -7.3957, longitude: 109.6961, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kebumen (Kebumen)', province: 'Jawa Tengah', latitude: -7.6684, longitude: 109.6537, timezone: 7, timezoneName: 'WIB' },
  { name: 'Purworejo (Purworejo)', province: 'Jawa Tengah', latitude: -7.7140, longitude: 110.0083, timezone: 7, timezoneName: 'WIB' },
  { name: 'Wonosobo (Wonosobo)', province: 'Jawa Tengah', latitude: -7.3583, longitude: 109.9052, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mungkid (Magelang)', province: 'Jawa Tengah', latitude: -7.5970, longitude: 110.2235, timezone: 7, timezoneName: 'WIB' },
  { name: 'Boyolali (Boyolali)', province: 'Jawa Tengah', latitude: -7.5457, longitude: 110.6106, timezone: 7, timezoneName: 'WIB' },
  { name: 'Klaten (Klaten)', province: 'Jawa Tengah', latitude: -7.7124, longitude: 110.5921, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sukoharjo (Sukoharjo)', province: 'Jawa Tengah', latitude: -7.6646, longitude: 110.8359, timezone: 7, timezoneName: 'WIB' },
  { name: 'Wonogiri (Wonogiri)', province: 'Jawa Tengah', latitude: -7.8151, longitude: 110.9257, timezone: 7, timezoneName: 'WIB' },
  { name: 'Karanganyar (Karanganyar)', province: 'Jawa Tengah', latitude: -7.5955, longitude: 110.9396, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sragen (Sragen)', province: 'Jawa Tengah', latitude: -7.4264, longitude: 111.0232, timezone: 7, timezoneName: 'WIB' },
  { name: 'Purwodadi (Grobogan)', province: 'Jawa Tengah', latitude: -7.0821, longitude: 110.9174, timezone: 7, timezoneName: 'WIB' },
  { name: 'Blora (Blora)', province: 'Jawa Tengah', latitude: -6.9697, longitude: 111.4149, timezone: 7, timezoneName: 'WIB' },
  { name: 'Rembang (Rembang)', province: 'Jawa Tengah', latitude: -6.7035, longitude: 111.3426, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pati (Pati)', province: 'Jawa Tengah', latitude: -6.7522, longitude: 111.0399, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kudus (Kudus)', province: 'Jawa Tengah', latitude: -6.8057, longitude: 110.8422, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jepara (Jepara)', province: 'Jawa Tengah', latitude: -6.5901, longitude: 110.6681, timezone: 7, timezoneName: 'WIB' },
  { name: 'Demak (Demak)', province: 'Jawa Tengah', latitude: -6.8914, longitude: 110.6384, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ungaran (Semarang)', province: 'Jawa Tengah', latitude: -7.1290, longitude: 110.4041, timezone: 7, timezoneName: 'WIB' },
  { name: 'Temanggung (Temanggung)', province: 'Jawa Tengah', latitude: -7.3153, longitude: 110.1819, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kendal (Kendal)', province: 'Jawa Tengah', latitude: -6.9228, longitude: 110.2036, timezone: 7, timezoneName: 'WIB' },
  { name: 'Batang (Batang)', province: 'Jawa Tengah', latitude: -6.9107, longitude: 109.7297, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kajen (Pekalongan)', province: 'Jawa Tengah', latitude: -7.0250, longitude: 109.5911, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pemalang (Pemalang)', province: 'Jawa Tengah', latitude: -6.8932, longitude: 109.3807, timezone: 7, timezoneName: 'WIB' },
  { name: 'Slawi (Tegal)', province: 'Jawa Tengah', latitude: -6.9954, longitude: 109.1279, timezone: 7, timezoneName: 'WIB' },
  { name: 'Brebes (Brebes)', province: 'Jawa Tengah', latitude: -6.8701, longitude: 109.0392, timezone: 7, timezoneName: 'WIB' },
  { name: 'Magelang', province: 'Jawa Tengah', latitude: -7.5037, longitude: 110.2215, timezone: 7, timezoneName: 'WIB' },
  { name: 'Surakarta', province: 'Jawa Tengah', latitude: -7.5693, longitude: 110.8295, timezone: 7, timezoneName: 'WIB' },
  { name: 'Salatiga', province: 'Jawa Tengah', latitude: -7.3304, longitude: 110.5008, timezone: 7, timezoneName: 'WIB' },
  { name: 'Semarang', province: 'Jawa Tengah', latitude: -6.9817, longitude: 110.4122, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pekalongan', province: 'Jawa Tengah', latitude: -6.8969, longitude: 109.6621, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tegal', province: 'Jawa Tengah', latitude: -6.8704, longitude: 109.1374, timezone: 7, timezoneName: 'WIB' },

  // --- DI YOGYAKARTA ---
  { name: 'Wates (Kulon Progo)', province: 'DI Yogyakarta', latitude: -7.8578, longitude: 110.1592, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bantul (Bantul)', province: 'DI Yogyakarta', latitude: -7.8862, longitude: 110.3278, timezone: 7, timezoneName: 'WIB' },
  { name: 'Wonosari (Gunungkidul)', province: 'DI Yogyakarta', latitude: -7.9641, longitude: 110.6015, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sleman (Sleman)', province: 'DI Yogyakarta', latitude: -7.7165, longitude: 110.3558, timezone: 7, timezoneName: 'WIB' },
  { name: 'Yogyakarta', province: 'DI Yogyakarta', latitude: -7.7999, longitude: 110.3914, timezone: 7, timezoneName: 'WIB' },

  // --- JAWA TIMUR ---
  { name: 'Pacitan (Pacitan)', province: 'Jawa Timur', latitude: -8.1945, longitude: 111.1032, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ponorogo (Ponorogo)', province: 'Jawa Timur', latitude: -7.8709, longitude: 111.4625, timezone: 7, timezoneName: 'WIB' },
  { name: 'Trenggalek (Trenggalek)', province: 'Jawa Timur', latitude: -8.0479, longitude: 111.7092, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tulungagung (Tulungagung)', province: 'Jawa Timur', latitude: -8.0644, longitude: 111.9007, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kanigoro (Blitar)', province: 'Jawa Timur', latitude: -8.1239, longitude: 112.2131, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ngasem (Kediri)', province: 'Jawa Timur', latitude: -7.8022, longitude: 112.0411, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kepanjen (Malang)', province: 'Jawa Timur', latitude: -8.1055, longitude: 112.5733, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lumajang (Lumajang)', province: 'Jawa Timur', latitude: -8.1352, longitude: 113.2244, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jember (Jember)', province: 'Jawa Timur', latitude: -8.1697, longitude: 113.7022, timezone: 7, timezoneName: 'WIB' },
  { name: 'Banyuwangi (Banyuwangi)', province: 'Jawa Timur', latitude: -8.2230, longitude: 114.3664, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bondowoso (Bondowoso)', province: 'Jawa Timur', latitude: -7.9144, longitude: 113.8219, timezone: 7, timezoneName: 'WIB' },
  { name: 'Situbondo (Situbondo)', province: 'Jawa Timur', latitude: -7.7073, longitude: 114.0018, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kraksaan (Probolinggo)', province: 'Jawa Timur', latitude: -7.7618, longitude: 113.4160, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bangil (Pasuruan)', province: 'Jawa Timur', latitude: -7.6490, longitude: 112.9052, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sidoarjo (Sidoarjo)', province: 'Jawa Timur', latitude: -7.4472, longitude: 112.7181, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mojosari (Mojokerto)', province: 'Jawa Timur', latitude: -7.4628, longitude: 112.4334, timezone: 7, timezoneName: 'WIB' },
  { name: 'Jombang (Jombang)', province: 'Jawa Timur', latitude: -7.5564, longitude: 112.2346, timezone: 7, timezoneName: 'WIB' },
  { name: 'Nganjuk (Nganjuk)', province: 'Jawa Timur', latitude: -7.6020, longitude: 111.9019, timezone: 7, timezoneName: 'WIB' },
  { name: 'Caruban (Madiun)', province: 'Jawa Timur', latitude: -7.5385, longitude: 111.6535, timezone: 7, timezoneName: 'WIB' },
  { name: 'Magetan (Magetan)', province: 'Jawa Timur', latitude: -7.6562, longitude: 111.3293, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ngawi (Ngawi)', province: 'Jawa Timur', latitude: -7.4013, longitude: 111.4454, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bojonegoro (Bojonegoro)', province: 'Jawa Timur', latitude: -7.1499, longitude: 111.8815, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tuban (Tuban)', province: 'Jawa Timur', latitude: -6.8961, longitude: 112.0651, timezone: 7, timezoneName: 'WIB' },
  { name: 'Lamongan (Lamongan)', province: 'Jawa Timur', latitude: -7.1210, longitude: 112.4154, timezone: 7, timezoneName: 'WIB' },
  { name: 'Gresik (Gresik)', province: 'Jawa Timur', latitude: -7.1706, longitude: 112.5997, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bangkalan (Bangkalan)', province: 'Jawa Timur', latitude: -7.0464, longitude: 112.7371, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sampang (Sampang)', province: 'Jawa Timur', latitude: -7.1875, longitude: 113.2373, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pamekasan (Pamekasan)', province: 'Jawa Timur', latitude: -7.1569, longitude: 113.4719, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sumenep (Sumenep)', province: 'Jawa Timur', latitude: -7.0140, longitude: 113.8635, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kediri', province: 'Jawa Timur', latitude: -7.8122, longitude: 112.0143, timezone: 7, timezoneName: 'WIB' },
  { name: 'Blitar', province: 'Jawa Timur', latitude: -8.0992, longitude: 112.1646, timezone: 7, timezoneName: 'WIB' },
  { name: 'Malang', province: 'Jawa Timur', latitude: -7.9778, longitude: 112.6338, timezone: 7, timezoneName: 'WIB' },
  { name: 'Probolinggo', province: 'Jawa Timur', latitude: -7.7537, longitude: 113.2142, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pasuruan', province: 'Jawa Timur', latitude: -7.6474, longitude: 112.9086, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mojokerto', province: 'Jawa Timur', latitude: -7.4628, longitude: 112.4334, timezone: 7, timezoneName: 'WIB' },
  { name: 'Madiun', province: 'Jawa Timur', latitude: -7.6244, longitude: 111.5206, timezone: 7, timezoneName: 'WIB' },
  { name: 'Surabaya', province: 'Jawa Timur', latitude: -7.2589, longitude: 112.7470, timezone: 7, timezoneName: 'WIB' },
  { name: 'Batu', province: 'Jawa Timur', latitude: -7.8625, longitude: 112.5134, timezone: 7, timezoneName: 'WIB' },

  // --- BANTEN ---
  { name: 'Pandeglang (Pandeglang)', province: 'Banten', latitude: -6.3169, longitude: 106.1148, timezone: 7, timezoneName: 'WIB' },
  { name: 'Rangkasbitung (Lebak)', province: 'Banten', latitude: -6.3608, longitude: 106.2462, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tigaraksa (Tangerang)', province: 'Banten', latitude: -6.2696, longitude: 106.4844, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ciruas (Serang)', province: 'Banten', latitude: -6.1153, longitude: 106.1520, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tangerang', province: 'Banten', latitude: -6.1644, longitude: 106.6411, timezone: 7, timezoneName: 'WIB' },
  { name: 'Cilegon', province: 'Banten', latitude: -6.0098, longitude: 106.0421, timezone: 7, timezoneName: 'WIB' },
  { name: 'Serang', province: 'Banten', latitude: -6.1197, longitude: 106.1735, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tangerang Selatan', province: 'Banten', latitude: -6.3216, longitude: 106.7077, timezone: 7, timezoneName: 'WIB' },

  // --- BALI ---
  { name: 'Negara (Jembrana)', province: 'Bali', latitude: -8.3573, longitude: 114.6369, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tabanan (Tabanan)', province: 'Bali', latitude: -8.5395, longitude: 115.1310, timezone: 8, timezoneName: 'WITA' },
  { name: 'Mangupura (Badung)', province: 'Bali', latitude: -8.6019, longitude: 115.1791, timezone: 8, timezoneName: 'WITA' },
  { name: 'Gianyar (Gianyar)', province: 'Bali', latitude: -8.5409, longitude: 115.3241, timezone: 8, timezoneName: 'WITA' },
  { name: 'Semarapura (Klungkung)', province: 'Bali', latitude: -8.5344, longitude: 115.4030, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bangli (Bangli)', province: 'Bali', latitude: -8.4618, longitude: 115.3525, timezone: 8, timezoneName: 'WITA' },
  { name: 'Amlapura (Karangasem)', province: 'Bali', latitude: -8.4388, longitude: 115.6122, timezone: 8, timezoneName: 'WITA' },
  { name: 'Singaraja (Buleleng)', province: 'Bali', latitude: -8.1252, longitude: 115.0928, timezone: 8, timezoneName: 'WITA' },
  { name: 'Denpasar', province: 'Bali', latitude: -8.6545, longitude: 115.2165, timezone: 8, timezoneName: 'WITA' },

  // --- NUSA TENGGARA BARAT ---
  { name: 'Gerung (Lombok Barat)', province: 'Nusa Tenggara Barat', latitude: -8.6814, longitude: 116.1367, timezone: 8, timezoneName: 'WITA' },
  { name: 'Praya (Lombok Tengah)', province: 'Nusa Tenggara Barat', latitude: -8.7061, longitude: 116.2700, timezone: 8, timezoneName: 'WITA' },
  { name: 'Selong (Lombok Timur)', province: 'Nusa Tenggara Barat', latitude: -8.6509, longitude: 116.5297, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sumbawa Besar (Sumbawa)', province: 'Nusa Tenggara Barat', latitude: -8.4895, longitude: 117.4197, timezone: 8, timezoneName: 'WITA' },
  { name: 'Dompu (Dompu)', province: 'Nusa Tenggara Barat', latitude: -8.5341, longitude: 118.4647, timezone: 8, timezoneName: 'WITA' },
  { name: 'Woha (Bima)', province: 'Nusa Tenggara Barat', latitude: -8.5565, longitude: 118.6702, timezone: 8, timezoneName: 'WITA' },
  { name: 'Taliwang (Sumbawa Barat)', province: 'Nusa Tenggara Barat', latitude: -8.7539, longitude: 116.8543, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tanjung (Lombok Utara)', province: 'Nusa Tenggara Barat', latitude: -8.3563, longitude: 116.1593, timezone: 8, timezoneName: 'WITA' },
  { name: 'Mataram', province: 'Nusa Tenggara Barat', latitude: -8.5827, longitude: 116.1081, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bima', province: 'Nusa Tenggara Barat', latitude: -8.4617, longitude: 118.7487, timezone: 8, timezoneName: 'WITA' },

  // --- NUSA TENGGARA TIMUR ---
  { name: 'Oelamasi (Kupang)', province: 'Nusa Tenggara Timur', latitude: -10.0728, longitude: 123.8645, timezone: 8, timezoneName: 'WITA' },
  { name: 'Soe (Timor Tengah Selatan)', province: 'Nusa Tenggara Timur', latitude: -9.8518, longitude: 124.2665, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kefamenanu (Timor Tengah Utara)', province: 'Nusa Tenggara Timur', latitude: -9.4569, longitude: 124.4751, timezone: 8, timezoneName: 'WITA' },
  { name: 'Atambua (Belu)', province: 'Nusa Tenggara Timur', latitude: -9.1059, longitude: 124.8736, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kalabahi (Alor)', province: 'Nusa Tenggara Timur', latitude: -8.2093, longitude: 124.5735, timezone: 8, timezoneName: 'WITA' },
  { name: 'Larantuka (Flores Timur)', province: 'Nusa Tenggara Timur', latitude: -8.3265, longitude: 123.0031, timezone: 8, timezoneName: 'WITA' },
  { name: 'Maumere (Sikka)', province: 'Nusa Tenggara Timur', latitude: -8.6166, longitude: 122.2081, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ende (Ende)', province: 'Nusa Tenggara Timur', latitude: -8.8434, longitude: 121.6622, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bajawa (Ngada)', province: 'Nusa Tenggara Timur', latitude: -8.7852, longitude: 120.9747, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ruteng (Manggarai)', province: 'Nusa Tenggara Timur', latitude: -8.6114, longitude: 120.4643, timezone: 8, timezoneName: 'WITA' },
  { name: 'Waingapu (Sumba Timur)', province: 'Nusa Tenggara Timur', latitude: -9.6608, longitude: 120.2613, timezone: 8, timezoneName: 'WITA' },
  { name: 'Waikabubak (Sumba Barat)', province: 'Nusa Tenggara Timur', latitude: -9.6473, longitude: 119.3940, timezone: 8, timezoneName: 'WITA' },
  { name: 'Lewoleba (Lembata)', province: 'Nusa Tenggara Timur', latitude: -8.3599, longitude: 123.4592, timezone: 8, timezoneName: 'WITA' },
  { name: 'Baa (Rote Ndao)', province: 'Nusa Tenggara Timur', latitude: -10.7578, longitude: 123.0626, timezone: 8, timezoneName: 'WITA' },
  { name: 'Labuan Bajo (Manggarai Barat)', province: 'Nusa Tenggara Timur', latitude: -8.4960, longitude: 119.8943, timezone: 8, timezoneName: 'WITA' },
  { name: 'Mbay (Nagekeo)', province: 'Nusa Tenggara Timur', latitude: -8.5755, longitude: 121.2811, timezone: 8, timezoneName: 'WITA' },
  { name: 'Waibakul (Sumba Tengah)', province: 'Nusa Tenggara Timur', latitude: -9.6227, longitude: 119.6004, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tambolaka (Sumba Barat Daya)', province: 'Nusa Tenggara Timur', latitude: -9.3917, longitude: 119.1810, timezone: 8, timezoneName: 'WITA' },
  { name: 'Borong (Manggarai Timur)', province: 'Nusa Tenggara Timur', latitude: -8.7495, longitude: 120.6086, timezone: 8, timezoneName: 'WITA' },
  { name: 'Seba (Sabu Raijua)', province: 'Nusa Tenggara Timur', latitude: -10.4528, longitude: 121.8780, timezone: 8, timezoneName: 'WITA' },
  { name: 'Betun (Malaka)', province: 'Nusa Tenggara Timur', latitude: -9.4446, longitude: 124.9176, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kupang', province: 'Nusa Tenggara Timur', latitude: -10.1539, longitude: 123.6194, timezone: 8, timezoneName: 'WITA' },

  // --- KALIMANTAN BARAT ---
  { name: 'Sambas (Sambas)', province: 'Kalimantan Barat', latitude: 1.3611, longitude: 109.3285, timezone: 7, timezoneName: 'WIB' },
  { name: 'Mempawah (Mempawah)', province: 'Kalimantan Barat', latitude: 0.3507, longitude: 108.9625, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sanggau (Sanggau)', province: 'Kalimantan Barat', latitude: 0.1235, longitude: 110.5960, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ketapang (Ketapang)', province: 'Kalimantan Barat', latitude: -1.8442, longitude: 109.9789, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sintang (Sintang)', province: 'Kalimantan Barat', latitude: 0.0787, longitude: 111.4955, timezone: 7, timezoneName: 'WIB' },
  { name: 'Putussibau (Kapuas Hulu)', province: 'Kalimantan Barat', latitude: 0.8793, longitude: 112.9254, timezone: 7, timezoneName: 'WIB' },
  { name: 'Bengkayang (Bengkayang)', province: 'Kalimantan Barat', latitude: 0.8691, longitude: 109.4975, timezone: 7, timezoneName: 'WIB' },
  { name: 'Ngabang (Landak)', province: 'Kalimantan Barat', latitude: 0.3748, longitude: 109.9383, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sekadau (Sekadau)', province: 'Kalimantan Barat', latitude: 0.0072, longitude: 110.9547, timezone: 7, timezoneName: 'WIB' },
  { name: 'Nanga Pinoh (Melawi)', province: 'Kalimantan Barat', latitude: -0.3769, longitude: 111.7644, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sukadana (Kayong Utara)', province: 'Kalimantan Barat', latitude: -1.2533, longitude: 109.9544, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sungai Raya (Kubu Raya)', province: 'Kalimantan Barat', latitude: -0.1269, longitude: 109.4040, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pontianak', province: 'Kalimantan Barat', latitude: -0.0221, longitude: 109.3381, timezone: 7, timezoneName: 'WIB' },
  { name: 'Singkawang', province: 'Kalimantan Barat', latitude: 0.9048, longitude: 108.9774, timezone: 7, timezoneName: 'WIB' },

  // --- KALIMANTAN TENGAH ---
  { name: 'Pangkalan Bun (Kotawaringin Barat)', province: 'Kalimantan Tengah', latitude: -2.6922, longitude: 111.6343, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sampit (Kotawaringin Timur)', province: 'Kalimantan Tengah', latitude: -2.5375, longitude: 112.9410, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kuala Kapuas (Kapuas)', province: 'Kalimantan Tengah', latitude: -2.9645, longitude: 114.4161, timezone: 7, timezoneName: 'WIB' },
  { name: 'Buntok (Barito Selatan)', province: 'Kalimantan Tengah', latitude: -1.7190, longitude: 114.8451, timezone: 7, timezoneName: 'WIB' },
  { name: 'Muara Teweh (Barito Utara)', province: 'Kalimantan Tengah', latitude: -0.9521, longitude: 114.8985, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kasongan (Katingan)', province: 'Kalimantan Tengah', latitude: -1.8807, longitude: 113.3992, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kuala Pembuang (Seruyan)', province: 'Kalimantan Tengah', latitude: -3.4138, longitude: 112.5417, timezone: 7, timezoneName: 'WIB' },
  { name: 'Sukamara (Sukamara)', province: 'Kalimantan Tengah', latitude: -2.7605, longitude: 111.1766, timezone: 7, timezoneName: 'WIB' },
  { name: 'Nanga Bulik (Lamandau)', province: 'Kalimantan Tengah', latitude: -2.1848, longitude: 111.4276, timezone: 7, timezoneName: 'WIB' },
  { name: 'Kuala Kurun (Gunung Mas)', province: 'Kalimantan Tengah', latitude: -1.1273, longitude: 113.8439, timezone: 7, timezoneName: 'WIB' },
  { name: 'Pulang Pisau (Pulang Pisau)', province: 'Kalimantan Tengah', latitude: -2.7164, longitude: 114.3047, timezone: 7, timezoneName: 'WIB' },
  { name: 'Puruk Cahu (Murung Raya)', province: 'Kalimantan Tengah', latitude: -0.6402, longitude: 114.5687, timezone: 7, timezoneName: 'WIB' },
  { name: 'Tamiang Layang (Barito Timur)', province: 'Kalimantan Tengah', latitude: -2.1153, longitude: 115.1692, timezone: 7, timezoneName: 'WIB' },
  { name: 'Palangkaraya', province: 'Kalimantan Tengah', latitude: -2.1740, longitude: 113.8803, timezone: 7, timezoneName: 'WIB' },

  // --- KALIMANTAN SELATAN ---
  { name: 'Pelaihari (Tanah Laut)', province: 'Kalimantan Selatan', latitude: -3.7995, longitude: 114.7826, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kotabaru (Kotabaru)', province: 'Kalimantan Selatan', latitude: -3.2362, longitude: 116.2280, timezone: 8, timezoneName: 'WITA' },
  { name: 'Martapura (Banjar)', province: 'Kalimantan Selatan', latitude: -3.4087, longitude: 114.8482, timezone: 8, timezoneName: 'WITA' },
  { name: 'Marabahan (Barito Kuala)', province: 'Kalimantan Selatan', latitude: -2.9783, longitude: 114.7658, timezone: 8, timezoneName: 'WITA' },
  { name: 'Rantau (Tapin)', province: 'Kalimantan Selatan', latitude: -2.9321, longitude: 115.1633, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kandangan (Hulu Sungai Selatan)', province: 'Kalimantan Selatan', latitude: -2.7865, longitude: 115.2659, timezone: 8, timezoneName: 'WITA' },
  { name: 'Barabai (Hulu Sungai Tengah)', province: 'Kalimantan Selatan', latitude: -2.5848, longitude: 115.3845, timezone: 8, timezoneName: 'WITA' },
  { name: 'Amuntai (Hulu Sungai Utara)', province: 'Kalimantan Selatan', latitude: -2.4189, longitude: 115.2543, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tanjung (Tabalong)', province: 'Kalimantan Selatan', latitude: -2.1644, longitude: 115.3824, timezone: 8, timezoneName: 'WITA' },
  { name: 'Batulicin (Tanah Bumbu)', province: 'Kalimantan Selatan', latitude: -3.4832, longitude: 115.9468, timezone: 8, timezoneName: 'WITA' },
  { name: 'Paringin (Balangan)', province: 'Kalimantan Selatan', latitude: -2.3636, longitude: 115.4711, timezone: 8, timezoneName: 'WITA' },
  { name: 'Banjarmasin', province: 'Kalimantan Selatan', latitude: -3.3275, longitude: 114.5890, timezone: 8, timezoneName: 'WITA' },
  { name: 'Banjarbaru', province: 'Kalimantan Selatan', latitude: -3.4386, longitude: 114.8311, timezone: 8, timezoneName: 'WITA' },

  // --- KALIMANTAN TIMUR ---
  { name: 'Tana Paser (Paser)', province: 'Kalimantan Timur', latitude: -1.9104, longitude: 116.1913, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tenggarong (Kutai Kartanegara)', province: 'Kalimantan Timur', latitude: -0.4428, longitude: 116.9987, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tanjung Redeb (Berau)', province: 'Kalimantan Timur', latitude: 2.1500, longitude: 117.5076, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sendawar (Kutai Barat)', province: 'Kalimantan Timur', latitude: -0.2365, longitude: 115.6964, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sangatta (Kutai Timur)', province: 'Kalimantan Timur', latitude: 0.5257, longitude: 117.6082, timezone: 8, timezoneName: 'WITA' },
  { name: 'Penajam (Penajam Paser Utara)', province: 'Kalimantan Timur', latitude: -1.3082, longitude: 116.7269, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ujoh Bilang (Mahakam Ulu)', province: 'Kalimantan Timur', latitude: 0.5057, longitude: 115.2708, timezone: 8, timezoneName: 'WITA' },
  { name: 'Balikpapan', province: 'Kalimantan Timur', latitude: -1.2763, longitude: 116.8278, timezone: 8, timezoneName: 'WITA' },
  { name: 'Samarinda', province: 'Kalimantan Timur', latitude: -0.4914, longitude: 117.1460, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bontang', province: 'Kalimantan Timur', latitude: 0.0695, longitude: 117.4442, timezone: 8, timezoneName: 'WITA' },

  // --- KALIMANTAN UTARA ---
  { name: 'Tanjung Selor (Bulungan)', province: 'Kalimantan Utara', latitude: 2.8409, longitude: 117.3981, timezone: 8, timezoneName: 'WITA' },
  { name: 'Malinau (Malinau)', province: 'Kalimantan Utara', latitude: 3.5519, longitude: 116.6221, timezone: 8, timezoneName: 'WITA' },
  { name: 'Nunukan (Nunukan)', province: 'Kalimantan Utara', latitude: 4.0771, longitude: 117.7189, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tideng Pale (Tana Tidung)', province: 'Kalimantan Utara', latitude: 3.6023, longitude: 116.9028, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tarakan', province: 'Kalimantan Utara', latitude: 3.3137, longitude: 117.6049, timezone: 8, timezoneName: 'WITA' },

  // --- SULAWESI UTARA ---
  { name: 'Lolak (Bolaang Mongondow)', province: 'Sulawesi Utara', latitude: 0.8706, longitude: 124.0244, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tondano (Minahasa)', province: 'Sulawesi Utara', latitude: 1.3008, longitude: 124.9109, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tahuna (Kepulauan Sangihe)', province: 'Sulawesi Utara', latitude: 3.6125, longitude: 125.4996, timezone: 8, timezoneName: 'WITA' },
  { name: 'Melonguane (Kepulauan Talaud)', province: 'Sulawesi Utara', latitude: 4.0058, longitude: 126.6819, timezone: 8, timezoneName: 'WITA' },
  { name: 'Amurang (Minahasa Selatan)', province: 'Sulawesi Utara', latitude: 1.2133, longitude: 124.5972, timezone: 8, timezoneName: 'WITA' },
  { name: 'Airmadidi (Minahasa Utara)', province: 'Sulawesi Utara', latitude: 1.4591, longitude: 124.9747, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ratahan (Minahasa Tenggara)', province: 'Sulawesi Utara', latitude: 1.0418, longitude: 124.7976, timezone: 8, timezoneName: 'WITA' },
  { name: 'Boroko (Bolaang Mongondow Utara)', province: 'Sulawesi Utara', latitude: 0.9065, longitude: 123.2591, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ondong Siau (Kep. Siau Tagulandang Biaro)', province: 'Sulawesi Utara', latitude: 2.7446, longitude: 125.3623, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tutuyan (Bolaang Mongondow Timur)', province: 'Sulawesi Utara', latitude: 0.7685, longitude: 124.6132, timezone: 8, timezoneName: 'WITA' },
  { name: 'Molibagu (Bolaang Mongondow Selatan)', province: 'Sulawesi Utara', latitude: 0.3835, longitude: 124.0479, timezone: 8, timezoneName: 'WITA' },
  { name: 'Manado', province: 'Sulawesi Utara', latitude: 1.4846, longitude: 124.8491, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bitung', province: 'Sulawesi Utara', latitude: 1.4454, longitude: 125.1820, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tomohon', province: 'Sulawesi Utara', latitude: 1.3145, longitude: 124.8274, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kotamobagu', province: 'Sulawesi Utara', latitude: 0.7435, longitude: 124.3127, timezone: 8, timezoneName: 'WITA' },

  // --- SULAWESI TENGAH ---
  { name: 'Luwuk (Banggai)', province: 'Sulawesi Tengah', latitude: -0.9943, longitude: 122.7885, timezone: 8, timezoneName: 'WITA' },
  { name: 'Poso (Poso)', province: 'Sulawesi Tengah', latitude: -1.3952, longitude: 120.7548, timezone: 8, timezoneName: 'WITA' },
  { name: 'Banawa (Donggala)', province: 'Sulawesi Tengah', latitude: -0.6785, longitude: 119.7526, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tolitoli (Toli-Toli)', province: 'Sulawesi Tengah', latitude: 1.0185, longitude: 120.7980, timezone: 8, timezoneName: 'WITA' },
  { name: 'Buol (Buol)', province: 'Sulawesi Tengah', latitude: 1.1691, longitude: 121.4098, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bungku (Morowali)', province: 'Sulawesi Tengah', latitude: -2.4809, longitude: 121.9343, timezone: 8, timezoneName: 'WITA' },
  { name: 'Salakan (Banggai Kepulauan)', province: 'Sulawesi Tengah', latitude: -1.3119, longitude: 123.2984, timezone: 8, timezoneName: 'WITA' },
  { name: 'Parigi (Parigi Moutong)', province: 'Sulawesi Tengah', latitude: -0.8054, longitude: 120.1603, timezone: 8, timezoneName: 'WITA' },
  { name: 'Ampana (Tojo Una Una)', province: 'Sulawesi Tengah', latitude: -0.9147, longitude: 121.5885, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sigi Biromaru (Sigi)', province: 'Sulawesi Tengah', latitude: -1.0474, longitude: 119.9503, timezone: 8, timezoneName: 'WITA' },
  { name: 'Banggai (Banggai Laut)', province: 'Sulawesi Tengah', latitude: -1.6063, longitude: 123.4964, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kolonodale (Morowali Utara)', province: 'Sulawesi Tengah', latitude: -1.9773, longitude: 121.3355, timezone: 8, timezoneName: 'WITA' },
  { name: 'Palu', province: 'Sulawesi Tengah', latitude: -0.9000, longitude: 119.8910, timezone: 8, timezoneName: 'WITA' },

  // --- SULAWESI SELATAN ---
  { name: 'Benteng (Kepulauan Selayar)', province: 'Sulawesi Selatan', latitude: -6.1202, longitude: 120.4663, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bulukumba (Bulukumba)', province: 'Sulawesi Selatan', latitude: -5.5582, longitude: 120.1931, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bantaeng (Bantaeng)', province: 'Sulawesi Selatan', latitude: -5.5532, longitude: 119.9672, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bontosunggu (Jeneponto)', province: 'Sulawesi Selatan', latitude: -5.6769, longitude: 119.7494, timezone: 8, timezoneName: 'WITA' },
  { name: 'Pattallassang (Takalar)', province: 'Sulawesi Selatan', latitude: -5.4255, longitude: 119.4406, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sungguminasa (Gowa)', province: 'Sulawesi Selatan', latitude: -5.1998, longitude: 119.4532, timezone: 8, timezoneName: 'WITA' },
  { name: 'Balangnipa (Sinjai)', province: 'Sulawesi Selatan', latitude: -5.1199, longitude: 120.2354, timezone: 8, timezoneName: 'WITA' },
  { name: 'Watampone (Bone)', province: 'Sulawesi Selatan', latitude: -4.5393, longitude: 120.3093, timezone: 8, timezoneName: 'WITA' },
  { name: 'Turikale (Maros)', province: 'Sulawesi Selatan', latitude: -5.0161, longitude: 119.5745, timezone: 8, timezoneName: 'WITA' },
  { name: 'Pangkajene (Pangkajene dan Kepulauan)', province: 'Sulawesi Selatan', latitude: -4.8457, longitude: 119.5598, timezone: 8, timezoneName: 'WITA' },
  { name: 'Barru (Barru)', province: 'Sulawesi Selatan', latitude: -4.4140, longitude: 119.6173, timezone: 8, timezoneName: 'WITA' },
  { name: 'Watansoppeng (Soppeng)', province: 'Sulawesi Selatan', latitude: -4.3644, longitude: 119.8978, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sengkang (Wajo)', province: 'Sulawesi Selatan', latitude: -4.1121, longitude: 120.0272, timezone: 8, timezoneName: 'WITA' },
  { name: 'Pangkajene Sidenreng (Sidenreng Rappang)', province: 'Sulawesi Selatan', latitude: -3.9331, longitude: 119.7693, timezone: 8, timezoneName: 'WITA' },
  { name: 'Pinrang (Pinrang)', province: 'Sulawesi Selatan', latitude: -3.8093, longitude: 119.6500, timezone: 8, timezoneName: 'WITA' },
  { name: 'Enrekang (Enrekang)', province: 'Sulawesi Selatan', latitude: -3.5883, longitude: 119.7703, timezone: 8, timezoneName: 'WITA' },
  { name: 'Belopa (Luwu)', province: 'Sulawesi Selatan', latitude: -3.3947, longitude: 120.3655, timezone: 8, timezoneName: 'WITA' },
  { name: 'Makale (Tana Toraja)', province: 'Sulawesi Selatan', latitude: -3.0865, longitude: 119.8571, timezone: 8, timezoneName: 'WITA' },
  { name: 'Masamba (Luwu Utara)', province: 'Sulawesi Selatan', latitude: -2.5499, longitude: 120.3462, timezone: 8, timezoneName: 'WITA' },
  { name: 'Malili (Luwu Timur)', province: 'Sulawesi Selatan', latitude: -2.6162, longitude: 121.1241, timezone: 8, timezoneName: 'WITA' },
  { name: 'Rantepao (Toraja Utara)', province: 'Sulawesi Selatan', latitude: -2.9736, longitude: 119.8948, timezone: 8, timezoneName: 'WITA' },
  { name: 'Makassar', province: 'Sulawesi Selatan', latitude: -5.1332, longitude: 119.4078, timezone: 8, timezoneName: 'WITA' },
  { name: 'Parepare', province: 'Sulawesi Selatan', latitude: -4.0278, longitude: 119.6333, timezone: 8, timezoneName: 'WITA' },
  { name: 'Palopo', province: 'Sulawesi Selatan', latitude: -3.0084, longitude: 120.2016, timezone: 8, timezoneName: 'WITA' },

  // --- SULAWESI TENGGARA ---
  { name: 'Kolaka (Kolaka)', province: 'Sulawesi Tenggara', latitude: -4.0608, longitude: 121.6161, timezone: 8, timezoneName: 'WITA' },
  { name: 'Unaaha (Konawe)', province: 'Sulawesi Tenggara', latitude: -3.8542, longitude: 122.0427, timezone: 8, timezoneName: 'WITA' },
  { name: 'Raha (Muna)', province: 'Sulawesi Tenggara', latitude: -4.7979, longitude: 122.7190, timezone: 8, timezoneName: 'WITA' },
  { name: 'Pasarwajo (Buton)', province: 'Sulawesi Tenggara', latitude: -5.4958, longitude: 122.8401, timezone: 8, timezoneName: 'WITA' },
  { name: 'Andolo (Konawe Selatan)', province: 'Sulawesi Tenggara', latitude: -4.3320, longitude: 122.2813, timezone: 8, timezoneName: 'WITA' },
  { name: 'Rumbia (Bombana)', province: 'Sulawesi Tenggara', latitude: -4.7472, longitude: 122.0111, timezone: 8, timezoneName: 'WITA' },
  { name: 'Wangi-Wangi (Wakatobi)', province: 'Sulawesi Tenggara', latitude: -5.3283, longitude: 123.5389, timezone: 8, timezoneName: 'WITA' },
  { name: 'Lasusua (Kolaka Utara)', province: 'Sulawesi Tenggara', latitude: -3.4901, longitude: 120.8875, timezone: 8, timezoneName: 'WITA' },
  { name: 'Wanggudu (Konawe Utara)', province: 'Sulawesi Tenggara', latitude: -3.5124, longitude: 122.1107, timezone: 8, timezoneName: 'WITA' },
  { name: 'Buranga (Buton Utara)', province: 'Sulawesi Tenggara', latitude: -4.8010, longitude: 122.9831, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tirawuta (Kolaka Timur)', province: 'Sulawesi Tenggara', latitude: -4.0005, longitude: 121.8619, timezone: 8, timezoneName: 'WITA' },
  { name: 'Langara (Konawe Kepulauan)', province: 'Sulawesi Tenggara', latitude: -4.0526, longitude: 122.9886, timezone: 8, timezoneName: 'WITA' },
  { name: 'Sawerigadi (Muna Barat)', province: 'Sulawesi Tenggara', latitude: -4.7917, longitude: 122.4942, timezone: 8, timezoneName: 'WITA' },
  { name: 'Labungkari (Buton Tengah)', province: 'Sulawesi Tenggara', latitude: -5.3164, longitude: 122.5320, timezone: 8, timezoneName: 'WITA' },
  { name: 'Batauga (Buton Selatan)', province: 'Sulawesi Tenggara', latitude: -5.6082, longitude: 122.6006, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kendari', province: 'Sulawesi Tenggara', latitude: -3.9729, longitude: 122.5117, timezone: 8, timezoneName: 'WITA' },
  { name: 'Bau Bau', province: 'Sulawesi Tenggara', latitude: -5.4851, longitude: 122.5848, timezone: 8, timezoneName: 'WITA' },

  // --- GORONTALO ---
  { name: 'Limboto (Gorontalo)', province: 'Gorontalo', latitude: 0.6290, longitude: 122.9809, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tilamuta (Boalemo)', province: 'Gorontalo', latitude: 0.5293, longitude: 122.3475, timezone: 8, timezoneName: 'WITA' },
  { name: 'Suwawa (Bone Bolango)', province: 'Gorontalo', latitude: 0.5574, longitude: 123.1439, timezone: 8, timezoneName: 'WITA' },
  { name: 'Marisa (Pohuwato)', province: 'Gorontalo', latitude: 0.7055, longitude: 121.7195, timezone: 8, timezoneName: 'WITA' },
  { name: 'Kwandang (Gorontalo Utara)', province: 'Gorontalo', latitude: 0.7909, longitude: 122.8687, timezone: 8, timezoneName: 'WITA' },
  { name: 'Gorontalo', province: 'Gorontalo', latitude: 0.5319, longitude: 123.0595, timezone: 8, timezoneName: 'WITA' },

  // --- SULAWESI BARAT ---
  { name: 'Pasangkayu (Pasangkayu)', province: 'Sulawesi Barat', latitude: -1.1737, longitude: 119.3772, timezone: 8, timezoneName: 'WITA' },
  { name: 'Mamuju (Mamuju)', province: 'Sulawesi Barat', latitude: -2.6897, longitude: 118.8845, timezone: 8, timezoneName: 'WITA' },
  { name: 'Mamasa (Mamasa)', province: 'Sulawesi Barat', latitude: -2.9556, longitude: 119.3629, timezone: 8, timezoneName: 'WITA' },
  { name: 'Polewali (Polewali Mandar)', province: 'Sulawesi Barat', latitude: -3.4077, longitude: 119.3112, timezone: 8, timezoneName: 'WITA' },
  { name: 'Banggae (Majene)', province: 'Sulawesi Barat', latitude: -3.5481, longitude: 118.9593, timezone: 8, timezoneName: 'WITA' },
  { name: 'Tobadak (Mamuju Tengah)', province: 'Sulawesi Barat', latitude: -2.0819, longitude: 119.3010, timezone: 8, timezoneName: 'WITA' },

  // --- MALUKU ---
  { name: 'Masohi (Maluku Tengah)', province: 'Maluku', latitude: -3.3043, longitude: 128.9541, timezone: 9, timezoneName: 'WIT' },
  { name: 'Langgur (Maluku Tenggara)', province: 'Maluku', latitude: -5.6829, longitude: 132.7173, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kepulauan Tanimbar', province: 'Maluku', latitude: -7.9701, longitude: 131.3123, timezone: 9, timezoneName: 'WIT' },
  { name: 'Namlea (Buru)', province: 'Maluku', latitude: -3.2592, longitude: 127.1028, timezone: 9, timezoneName: 'WIT' },
  { name: 'Bula (Seram Bagian Timur)', province: 'Maluku', latitude: -3.1037, longitude: 130.4886, timezone: 9, timezoneName: 'WIT' },
  { name: 'Piru (Seram Bagian Barat)', province: 'Maluku', latitude: -3.0667, longitude: 128.2300, timezone: 9, timezoneName: 'WIT' },
  { name: 'Dobo (Kepulauan Aru)', province: 'Maluku', latitude: -5.7752, longitude: 134.2146, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tiakur (Maluku Barat Daya)', province: 'Maluku', latitude: -8.1480, longitude: 127.8016, timezone: 9, timezoneName: 'WIT' },
  { name: 'Namrole (Buru Selatan)', province: 'Maluku', latitude: -3.8378, longitude: 126.7343, timezone: 9, timezoneName: 'WIT' },
  { name: 'Ambon', province: 'Maluku', latitude: -3.6943, longitude: 128.1813, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tual', province: 'Maluku', latitude: -5.6347, longitude: 132.7517, timezone: 9, timezoneName: 'WIT' },

  // --- MALUKU UTARA ---
  { name: 'Jailolo (Halmahera Barat)', province: 'Maluku Utara', latitude: 1.0805, longitude: 127.4802, timezone: 9, timezoneName: 'WIT' },
  { name: 'Weda (Halmahera Tengah)', province: 'Maluku Utara', latitude: 0.3304, longitude: 127.8703, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tobelo (Halmahera Utara)', province: 'Maluku Utara', latitude: 1.7282, longitude: 127.9922, timezone: 9, timezoneName: 'WIT' },
  { name: 'Labuha (Halmahera Selatan)', province: 'Maluku Utara', latitude: -0.6455, longitude: 127.5050, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sanana (Kepulauan Sula)', province: 'Maluku Utara', latitude: -2.0070, longitude: 125.9641, timezone: 9, timezoneName: 'WIT' },
  { name: 'Maba (Halmahera Timur)', province: 'Maluku Utara', latitude: 0.6774, longitude: 128.2841, timezone: 9, timezoneName: 'WIT' },
  { name: 'Daruba (Pulau Morotai)', province: 'Maluku Utara', latitude: 2.0133, longitude: 128.2837, timezone: 9, timezoneName: 'WIT' },
  { name: 'Bobong (Pulau Taliabu)', province: 'Maluku Utara', latitude: -1.9474, longitude: 124.3872, timezone: 9, timezoneName: 'WIT' },
  { name: 'Ternate', province: 'Maluku Utara', latitude: 0.7858, longitude: 127.3878, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tidore Kepulauan', province: 'Maluku Utara', latitude: 0.6716, longitude: 127.4467, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA ---
  { name: 'Sentani (Jayapura)', province: 'Papua', latitude: -2.5499, longitude: 140.4771, timezone: 9, timezoneName: 'WIT' },
  { name: 'Serui (Kepulauan Yapen)', province: 'Papua', latitude: -1.8741, longitude: 136.2371, timezone: 9, timezoneName: 'WIT' },
  { name: 'Biak (Biak Numfor)', province: 'Papua', latitude: -1.1707, longitude: 136.0902, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sarmi (Sarmi)', province: 'Papua', latitude: -1.8686, longitude: 138.7442, timezone: 9, timezoneName: 'WIT' },
  { name: 'Waris (Keerom)', province: 'Papua', latitude: -2.9087, longitude: 140.7733, timezone: 9, timezoneName: 'WIT' },
  { name: 'Botawa (Waropen)', province: 'Papua', latitude: -2.2408, longitude: 136.3795, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sorendiweri (Supiori)', province: 'Papua', latitude: -0.7307, longitude: 135.7326, timezone: 9, timezoneName: 'WIT' },
  { name: 'Burmeso (Mamberamo Raya)', province: 'Papua', latitude: -2.3708, longitude: 138.0499, timezone: 9, timezoneName: 'WIT' },
  { name: 'Jayapura', province: 'Papua', latitude: -2.5626, longitude: 140.6926, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA BARAT ---
  { name: 'Manokwari (Manokwari)', province: 'Papua Barat', latitude: -0.8908, longitude: 134.0401, timezone: 9, timezoneName: 'WIT' },
  { name: 'Fakfak (Fak Fak)', province: 'Papua Barat', latitude: -2.9289, longitude: 132.2936, timezone: 9, timezoneName: 'WIT' },
  { name: 'Bintuni (Teluk Bintuni)', province: 'Papua Barat', latitude: -2.0350, longitude: 133.7318, timezone: 9, timezoneName: 'WIT' },
  { name: 'Rasiei (Teluk Wondama)', province: 'Papua Barat', latitude: -2.8277, longitude: 134.5357, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kaimana (Kaimana)', province: 'Papua Barat', latitude: -3.6397, longitude: 133.7401, timezone: 9, timezoneName: 'WIT' },
  { name: 'Ransiki (Manokwari Selatan)', province: 'Papua Barat', latitude: -1.5064, longitude: 134.1686, timezone: 9, timezoneName: 'WIT' },
  { name: 'Anggi (Pegunungan Arfak)', province: 'Papua Barat', latitude: -1.3250, longitude: 133.9166, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA SELATAN ---
  { name: 'Merauke (Merauke)', province: 'Papua Selatan', latitude: -8.5087, longitude: 140.4097, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tanah Merah (Boven Digoel)', province: 'Papua Selatan', latitude: -6.1004, longitude: 140.3206, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kepi (Mappi)', province: 'Papua Selatan', latitude: -6.5281, longitude: 139.3193, timezone: 9, timezoneName: 'WIT' },
  { name: 'Agats (Asmat)', province: 'Papua Selatan', latitude: -5.5409, longitude: 138.1368, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA TENGAH ---
  { name: 'Nabire (Nabire)', province: 'Papua Tengah', latitude: -3.3634, longitude: 135.5039, timezone: 9, timezoneName: 'WIT' },
  { name: 'Mulia (Puncak Jaya)', province: 'Papua Tengah', latitude: -3.7162, longitude: 137.9878, timezone: 9, timezoneName: 'WIT' },
  { name: 'Enarotali (Paniai)', province: 'Papua Tengah', latitude: -3.9414, longitude: 136.4216, timezone: 9, timezoneName: 'WIT' },
  { name: 'Timika (Mimika)', province: 'Papua Tengah', latitude: -4.4559, longitude: 136.8537, timezone: 9, timezoneName: 'WIT' },
  { name: 'Ilaga (Puncak)', province: 'Papua Tengah', latitude: -3.9716, longitude: 137.6418, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kigamani (Dogiyai)', province: 'Papua Tengah', latitude: -4.0046, longitude: 136.0378, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sugapa (Intan Jaya)', province: 'Papua Tengah', latitude: -3.7405, longitude: 137.0440, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tigi (Deiyai)', province: 'Papua Tengah', latitude: -4.0322, longitude: 136.2990, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA PEGUNUNGAN ---
  { name: 'Wamena (Jayawijaya)', province: 'Papua Pegunungan', latitude: -4.0993, longitude: 138.9431, timezone: 9, timezoneName: 'WIT' },
  { name: 'Oksibil (Pegunungan Bintang)', province: 'Papua Pegunungan', latitude: -4.8909, longitude: 140.6399, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sumohai (Yahukimo)', province: 'Papua Pegunungan', latitude: -4.8869, longitude: 139.5205, timezone: 9, timezoneName: 'WIT' },
  { name: 'Karubaga (Tolikara)', province: 'Papua Pegunungan', latitude: -3.6823, longitude: 138.4735, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kobakma (Mamberamo Tengah)', province: 'Papua Pegunungan', latitude: -3.6716, longitude: 139.0608, timezone: 9, timezoneName: 'WIT' },
  { name: 'Elelim (Yalimo)', province: 'Papua Pegunungan', latitude: -3.7789, longitude: 139.3832, timezone: 9, timezoneName: 'WIT' },
  { name: 'Tiom (Lanny Jaya)', province: 'Papua Pegunungan', latitude: -3.9236, longitude: 138.4496, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kenyam (Nduga)', province: 'Papua Pegunungan', latitude: -4.4069, longitude: 138.2394, timezone: 9, timezoneName: 'WIT' },

  // --- PAPUA BARAT DAYA ---
  { name: 'Aimas (Sorong)', province: 'Papua Barat Daya', latitude: -0.9882, longitude: 131.3662, timezone: 9, timezoneName: 'WIT' },
  { name: 'Teminabuan (Sorong Selatan)', province: 'Papua Barat Daya', latitude: -1.4752, longitude: 132.0856, timezone: 9, timezoneName: 'WIT' },
  { name: 'Waisai (Raja Ampat)', province: 'Papua Barat Daya', latitude: -0.4185, longitude: 130.8288, timezone: 9, timezoneName: 'WIT' },
  { name: 'Fef (Tambrauw)', province: 'Papua Barat Daya', latitude: -0.4973, longitude: 132.0881, timezone: 9, timezoneName: 'WIT' },
  { name: 'Kumurkek (Maybrat)', province: 'Papua Barat Daya', latitude: -1.2573, longitude: 132.4986, timezone: 9, timezoneName: 'WIT' },
  { name: 'Sorong', province: 'Papua Barat Daya', latitude: -0.8811, longitude: 131.2876, timezone: 9, timezoneName: 'WIT' },
];

export const DEFAULT_CITY: City =
  INDONESIA_CITIES.find((c) => c.name === "Jakarta Pusat") ?? INDONESIA_CITIES[0];
